### ISSUE TITLE
AWS Integration and Kubernetes monitoring using Terraform

### ISSUE THREAD

**Issue by selvan1978** [newrelic/terraform-provider-newrelic#786] opened 2020-07-23 10:12 UTC
### Feature Description

We have configured EKS cluster in AWS and as of now Infrastructure monitoring configured through manually (AWS Integration and Kubernetes Options). We would like to place similar set of monitoring using Terraform.

**Comment by jthurman42** [comment] 2020-07-24 17:57
Thank you for the feature request.  Now that we have released the 2.x provider, we have enabled the ability to add Cloud integration configuration. That work is currently in our backlog, and we hope to get to it in the near term.  For updates please watch the initial ticket.

Duplicate of #62

**Closed by jthurman42** 2020-07-24 17:57 UTC
