### ISSUE TITLE
newrelic_notification_channel not displaying pagerduty service name - still functions and sends notifications. 

### ISSUE THREAD

**Issue by benjamin-lykins** [newrelic/terraform-provider-newrelic#2407] opened 2023-06-28 17:20 UTC
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [ ] Any related [log output](#debug-output)

### Terraform Version
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v3.25.0
+ provider registry.terraform.io/pagerduty/pagerduty v2.15.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_notification_channel`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration

```
newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.0"
    }

provider "newrelic" {
  account_id = local.newrelic_account
  api_key    = local.newrelic_api
  region     = "US"
}
```

```
resource "newrelic_notification_channel" "this" {
  for_each = toset(var.newrelic_monitors)
  account_id     = local.newrelic_account
  name           = "XXXX"
  type           = "PAGERDUTY_ACCOUNT_INTEGRATION"
  destination_id = one(newrelic_notification_destination.this.*.id)
  product        = "IINT" // (Workflows)

  property {
    key = "summary"
    value = "{{ annotations.title.[0] }}"
  }

  property {
    key = "service"
    value = "${pagerduty_service.this[each.value].id}"
  }

  property {
    key = "email"
    value = "XXXX"
  }

  // must be valid json
  property {
    key   = "customDetails"
    value = <<-EOT
            {
            "id":{{json issueId}},
            "IssueURL":{{json issuePageUrl}},
            "NewRelic priority":{{json priority}},
            "Total Incidents":{{json totalIncidents}},
            "Impacted Entities":"{{#each entitiesData.names}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}",
            "Runbook":"{{#each accumulations.runbookUrl}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}",
            "Description":"{{#each annotations.description}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}",
            "isCorrelated":{{json isCorrelated}},
            "Alert Policy Names":"{{#each accumulations.policyName}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}",
            "Alert Condition Names":"{{#each accumulations.conditionName}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}",
            "Workflow Name":{{json workflowName}}
            }
        EOT
  }

depends_on = [pagerduty_service.this, newrelic_notification_destination.this]

}
```

### Actual Behavior
What actually happened?

Resource applies correctly, however, in the UI it does not properly display the service field. Expecting it to show the service name that it will send notifications to, but it comes up blank. When checking via NerdGraph, it does list the Pagerduty service ID properly. 

Seems like there is some disconnect when doing it via Terraform versus the GUI, where it properly displays the service name. 

### Expected Behavior
What should have happened?

Service name shows up when viewing in the UI. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by lzaga-newrelic** [comment] 2023-07-02 09:52
Hi @benjamin-lykins 
Thank you for your report.

We are familiar with this [issue](https://github.com/newrelic/terraform-provider-newrelic/issues/2093) and it is a bug on the UI side indeed. We have a task for addressing this and hopefully will take care of it soon.

**Comment by benjamin-lykins** [comment] 2023-07-05 16:31
Thank you @lzaga-newrelic and sorry for not catching that this was already opened.

**Comment by pranav-new-relic** [comment] 2023-07-17 04:54
@benjamin-lykins since it appears that this is a duplicate of #2093, I shall go ahead and close this - just as an effort to help us find unique issues :) you can follow the aforementioned thread for updates. Thank you for reporting!

cc @lzaga-newrelic

**Closed by pranav-new-relic** 2023-07-17 04:54 UTC
Labels: bug, group-notifications
