### ISSUE TITLE
Manage Services on Azure Integration 

### ISSUE THREAD

**Issue by ironf1st** [newrelic/terraform-provider-newrelic#1747] opened 2022-04-05 19:57 UTC
### Feature Description
I would like to be able to manage the services that the Azure Integration will monitor. Currently the provider can create the integration via the `newrelic_cloud_azure_link_account` resource, but once the Integration is created we either have to interact directly with the API or click through the UI under Infrastructure -> Azure -> Azure services and select the Azure services to monitor. 

This could look something like this:

```hcl
resource "newrelic_cloud_azure_services" "self" {
  azure_account_id = newrelic_cloud_azure_link_account.self.id
  monitored_services = [ "App Service", "Containers", " Data Factory", "Key Vault" ] # This could also accept "all" to enable all of the services supported by the integration
}
```

Ideally any individual service configuration should also be possible to be done via this resource or a related resource so that the setup configuration of the Azure Integration can be done entirely via Terraform.

### Additional context
This request seems related to this issue https://github.com/newrelic/terraform-provider-newrelic/issues/62 but is AWS centric.

**Comment by kidk** [comment] 2022-04-06 10:15
Thanks for suggestion @ironf1st 

Good news is that we're working on this right now 😄  https://github.com/newrelic/terraform-provider-newrelic/pull/1737

I'll close this for now as this is a duplicate of #62 

We hope to have this out as soon as possible, but with any new resource we are extra careful to have it right the first team, as making breaking changes to existing resources is a pain. 

Thanks for your patience.

**Closed by kidk** 2022-04-06 10:15 UTC
