### ISSUE TITLE
newrelic_api_access_key throws APIAccessKeyErrorInterface

### ISSUE THREAD

**Issue by andrea-cuttone** [newrelic/terraform-provider-newrelic#1418] opened 2021-08-16 11:22 UTC
Hello

I am trying to create a `newrelic_api_access_key` this way:

```
resource "newrelic_api_access_key" "my_key" {
  account_id  = 123456
  key_type    = "INGEST"
  ingest_type = "LICENSE"
  name        = "my_key"
}
```

but when I `terraform apply` I get:

`Error: json: cannot unmarshal object into Go struct field .data.apiAccessCreateKeys.errors of type apiaccess.APIAccessKeyErrorInterface`

My setup:
- terraform v0.12.31
- NewRelic provider ~> 2.24.1

**Comment by esokoloff** [comment] 2022-04-01 12:48
Is there any progress on this issue?

**Comment by kidk** [comment] 2022-04-06 10:51
hi @andrea-cuttone Thanks for your patience on this.

I haven't been able to reproduce this, and since its' been a long time I'll close this issue.

Please reply in this ticket if this is still a problem for you with the latest version.

Thanks a lot

**Comment by xorxsan** [comment] 2022-06-03 09:23
Hi,

   I've come across this issue.
   This is the response I believe cannot be unmarshalled:
```
{
 "data": {
  "apiAccessCreateKeys": {
   "createdKeys": null,
   "errors": [
    {
     "accountId": account-id,
     "id": null,
     "ingestErrorType": "FORBIDDEN",
     "ingestType": "LICENSE",
     "message": "You do not have permission to create this key.",
     "type": "INGEST"
    }
   ]
  }
 }
}
```
It would be nice if this error could be correctly unmarshalled, instead of getting an exception.

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.46.1
```

**Comment by kidk** [comment] 2022-06-07 07:49
Thanks @xorxsan We'll take a look

**Comment by relsqui** [comment] 2022-06-30 20:55
We also got this error, with Terraform 1.2.3 and New Relic 2.46.0. I don't know how to track down the details of the response like the above commenter did, but with that clue I found an authentication problem in our configuration, and fixing it unblocked us. So our error response probably looked a lot like that one. :)

**Comment by pranav-new-relic** [comment] 2023-03-23 09:40
Hi @andrea-cuttone and @xorxsan - thanks for reporting this issue, and your patience with this. We've been able to reproduce the issue, and find that the issue occurs when the `account_id` specified is that of a 'basic' New Relic account, which is why you may see in the response of the API (quoted by @xorxsan) that access is forbidden to this resource. 

> ```{
>  "data": {
>   "apiAccessCreateKeys": {
>    "createdKeys": null,
>    "errors": [
>     {
>      "accountId": account-id,
>      "id": null,
>      "ingestErrorType": "FORBIDDEN",
>      "ingestType": "LICENSE",
>      "message": "You do not have permission to create this key.",
>      "type": "INGEST"
>     }
>    ]
>   }
>  }
> }

However, upon trying the same with a 'full platform' New Relic account, we haven't been able to reproduce the issue; i.e. we've been able to create an Ingest License Key, using a 'full platform' account. This hints at the fact that this issue could have been caused by the use of a 'basic' New Relic account added to an organization, which does not comprise the privileges needed to create Ingest - License Keys for the organization. The aforementioned API response you see is the GUI equivalent of the following, when you try creating Ingest - License keys from the New Relic UI, using a 'basic' account.

<img width="340" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/127438038/227159971-f08ea134-c560-476f-b19a-87b40e24ecfe.png">

We'd kindly urge you to try creating the resource using a New Relic account that is not 'basic' - you can read more about New Relic account privileges here, and how that restricts access to APIs (which the Terraform provider depends on).

- https://newrelic.com/pricing#pricing_plan-user
- https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#license-key
- https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-type/#api-access

We shall add a note to elucidate on this in the Terraform provider's docs, and subsequently, work on fixing the error message, based on priority. Please let us know if you still face the issue with a non 'basic' New Relic account. Thank you!

**Comment by pranav-new-relic** [comment] 2023-04-07 09:53
Hey everyone, we've added code corrections to address this issue - the fix is now live with the latest version of the Terraform Provider, [v.3.20.2](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.20.2). The error message has been unmarshalled into the following message that is obtained from the API - 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/127438038/230588077-ae838381-c4f1-4d58-a50b-ddc9c3bbb134.png">

Closing the issue - thank you for reporting this!

**Closed by pranav-new-relic** 2023-04-07 09:53 UTC
Labels: bug, group-general
