### ISSUE TITLE
newrelic_infra_alert_condition should support "description" field

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/terraform-provider-newrelic#779] opened 2020-07-21 11:55 UTC
### Feature Description
According to documentation, it is possible to configure description for infra alert conditions:
https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/alert-condition-descriptions

At the moment terraform resource **newrelic_infra_alert_condition**  is not supporting this.

**Comment by skyzyx** [comment] 2020-07-22 23:48
This looks like a dupe of mine. https://github.com/newrelic/terraform-provider-newrelic/issues/613

**Comment by dzadonskii** [comment] 2020-07-23 12:19
Not really. `newrelic_infra_alert_condition` is performing better than `newrelic_nrql_alert_condition` in case of Public cloud integration and in my case supporte recommended to use that . Besides the WebUI support "Description" field when setting up alerts but this functionality is missing in terraform provider.

**Closed** 2020-07-25 00:01 UTC
Labels: enhancement

**Comment by sanderblue** [comment] 2020-07-29 15:43
@echoAlexey [v2.4.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.4.0) adds support for the `description` attribute for the `newrelic_infra_alert_condition` resource. 😎
