### ISSUE TITLE
Please provide a way to integrate all other aws services to newrelic using API polling method, as it is becoming difficult for us to automate the process of integration using api polling method

### ISSUE THREAD

**Issue by Kashish-pandita-01** [newrelic/terraform-provider-newrelic#2364] opened 2023-05-07 12:50 UTC

**Comment by pranav-new-relic** [comment] 2023-05-08 03:37
Hi @Kashish-pandita-01, thank you for reporting this issue. We currently have two other open issues to address the addition of AWS integrations to Terraform, which have been listed below. We shall be working on this soon, based on priority, and would kindly request you to follow the issues mentioned below for updates. Closing this issue, as this would be a duplicate of the issues listed below - thanks.

https://github.com/newrelic/terraform-provider-newrelic/issues/2253
https://github.com/newrelic/terraform-provider-newrelic/issues/2258

**Closed by pranav-new-relic** 2023-05-08 03:37 UTC
