### ISSUE TITLE
"Not found" error when resource is deleted from NR platform

### ISSUE THREAD

**Issue by thedebugger** [newrelic/terraform-provider-newrelic#1430] opened 2021-09-08 05:12 UTC
### Terraform Version
```
Terraform v0.14.8
+provider registry.terraform.io/newrelic/newrelic v2.23.0
```

### Affected Resource(s)
possibly alert policy, alert condition and dashboard one

### Terraform Configuration
https://gist.github.com/thedebugger/718b536f3ae06170fd00a3e0c94ba212

### Actual Behavior

Error: Not Found

### Expected Behavior
NR provider/terraform should print the error message with the resources that are affected and/or recreate the resources if not found.

### Steps to Reproduce
* Create an alert and alert policy
* Delete the alert
* run terraform plan 

### Debug Output
https://gist.github.com/thedebugger/89ff189b29213d7f30d08f0087c0e2b2

### Panic Output
n/a

### Important Factoids
no

### References
- Possibly regression of https://github.com/newrelic/terraform-provider-newrelic/issues/860

**Comment by kidk** [comment] 2022-02-16 13:15
hi @thedebugger Could you try with the most recent version of the Terraform provider? We've been running tests locally and have been unable to reproduce the issue. 

If it still fails on your side, let me know if there's any changes to your HCL files.

**Comment by thedebugger** [comment] 2022-02-25 17:44
@kidk thanks! did you try deleting it from New relic UI? That makes the object orphan in NR terraform. You folks can close it for now and i can reopen it if i run into this again?

**Comment by kidk** [comment] 2022-02-28 08:52
We did, deleted the policy, the condition, the policy and the condition. I'll close it for now, but if you see it again let us know.

**Comment by kidk** [comment] 2022-07-12 06:36
quote from @gregc-88 in #1881 
```
Spun this into a new issue since the referenced issue was closed in Feb.

This is the second time I've found TF managed objects deleted by other staff with NR access. Aside from stern messaging stating not to do this, is there a preferred best practice for easily finding missing objects? Or is that workflow not necessary when the provider is able to recognize objects are missing and need to be recreated?
```

**Comment by kidk** [comment] 2022-07-12 06:37
@gregc-88 Is this also related to alert policies or conditions? We had trouble reproducing this in the past, so anything you can share about your environment is going to help.

**Comment by gregc-88** [comment] 2022-07-12 13:51
I've seen it with a muting policy and an alert. 

- The muting policy got deleted by a teammate who wasn't familiar with NR. 
- In the case of an alert, it was a deprecated format (outlier alert), so I'm not sure if it got deleted by a user or by the NR platform bc the functions no longer exist to support that alert.

In both cases, the result was the same. 
- Non-descript error in stdout when plan or apply is run. 
- Check debug logs for clues. I found hints of this with null values in the muting policy, but did not see what object the not found errors related to for the alert
- Manually check the UI to see what was missing
- Delete the missing item from the state file
- Tf plan and apply work again

**Comment by kidk** [comment] 2022-07-13 10:26
Awesome, thanks for the info @gregc-88 I've been able to reproduce it.

**Closed** 2022-07-14 14:29 UTC
Labels: group-general

**Comment by kidk** [comment] 2022-07-15 07:18
This will go out with the next release.
