### ISSUE TITLE
Workflow Implementation

### ISSUE THREAD

**Issue by ajlile98** [newrelic/terraform-provider-newrelic#1907] opened 2022-08-01 04:08 UTC
### Feature Description
Implement a Workflow Resource to be able to create/update/destroy the New Alerts/Ai feature Workflow.

### Describe Alternatives
The alternatives are notification channels, but as per New Relic, these are being phased out in October 2022 (https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436)

### Additional context
https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows/

**Comment by kidk** [comment] 2022-08-01 06:42
Duplicate of #873 The work is in progress and should be released in the coming weeks.

**Closed by kidk** 2022-08-01 06:42 UTC
