### ISSUE TITLE
Default account_id to the Account Defined in the Provider

### ISSUE THREAD

**Issue by ironf1st** [newrelic/terraform-provider-newrelic#1713] opened 2022-03-18 17:22 UTC
### Feature Description
Resources that currently can accept `account_id` as an argument should always default to the `account_id` defined in the provider block. 

For example these resources always require the account_id:
`newrelic_cloud_azure_link_account`
`newrelic_cloud_gcp_link_account`

And these resources for example will operate based on the account the API key is for unless specified:
`newrelic_alert_channel`
`newrelic_alert_muting_rule`
`newrelic_alert_policy`
`newrelic_api_access_key`

The current behavior leads to resources being created in unexpected accounts, unnecessary duplication of code, and is an anti-pattern to how [Terraform suggests to handle accounts/regions](https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations).

**Comment by mbazhlekova** [comment] 2022-03-18 19:25
@ironf1st Looks like those values were mistakenly marked as `Required` in the resource schema. I'll put out a fix for that this afternoon.

**Comment by ironf1st** [comment] 2022-03-18 19:38
Thanks for the quick response @mbazhlekova. What about all of the resources where the `account_id` is optional and default to whatever account the API key is tied to? To me this seems very backwards. I would rather error because I'm using the wrong API key than create resources in the wrong account or destroy resources on accident.

**Comment by kidk** [comment] 2022-03-21 08:37
Can you give an example of such a resource @ironf1st? If there is an accountID argument the resource should support multiple accounts, and error out if I can't create the resource in the specific accounts. If there is no accountID argument the resource will use the account ID linked to the API key.

For reference: The resources without an accountId field will slowly disappear as they are using the REST API. Our plan is to migrate all resources to the new GraphQL API as soon as possible. The resources currently remaining either don't have a GraphQL API yet, or we haven't had the chance to make the change.

**Comment by ironf1st** [comment] 2022-03-21 21:38
@kidk These 2 resources can receive accountID as an optional argument:

`newrelic_alert_channel`
`newrelic_alert_policy`

In the provider documentation each resource says that it will default to the account associated with the API key if not specified. 

And then these two accept it as an argument with it being required for `newrelic_api_access_key`:

`newrelic_alert_muting_rule`
`newrelic_api_access_key`

Why have this behavior if I have defined an `account_id` in the provider block? If I have an `account_id` in the provider block, terraform should try to create these resources in the account I've specified. Having some resources default to being created somewhere else if I'm either intentionally or unintentionally using an API key for another account is not good. I could accidentally destroy resources in a child account and create resources in the root New Relic account if I'm using an API key created in the root account.

**Comment by kidk** [comment] 2022-03-22 08:49
Thanks for the details @ironf1st 

`newrelic_alert_channel` and `newrelic_alert_policy` incorrectly show the warning. I've created a pull request to fix those: #1721 

> Why have this behavior if I have defined an account_id in the provider block?
This was an often requested feature because of the account structure in New Relic. Many customers would like to create resources (alerts, dashboards) in multiple accounts, using the same API key.

> Having some resources default to being created somewhere else if I'm either intentionally or unintentionally using an API key for another account is not good.
I'm not sure if I fully understand this. 

For the new API resources we will always try to set the accountId (either from provider block, or resource), and those requests will fail if the API key does not have access to those accounts. It should never create resources in different accounts.

For the old API we will indeed create the resource in the account linked to the API key, and changing the accountId in provider will not change that. I will double check with the team to see if we can throw an error in this case. As mentioned these resources are going away, so this problem will disappear over time. 

> I could accidentally destroy resources in a child account and create resources in the root New Relic account if I'm using an API key created in the root account.
It's indeed possible that resources are created in different accounts than expected, especially for the old API resources. As far as I know it's not possible that we unexpectedly delete unlinked resources, as we do our checks on unique ID's. If you have found a case where this does happen, please let us know so we can fix it. 


Would it be possible to share the specific use-case you're encountering or the problem it caused for you? We're always looking to improve our documentation and code to avoid confusion like this, so any details you can share will be helpful.

**Comment by kidk** [comment] 2022-04-19 08:34
Closing this for now as it's expected behavior. Feel free to comment on this ticket with further questions and issues if needed.

**Closed by kidk** 2022-04-19 08:34 UTC
Labels: bug, waiting-response
