### ISSUE TITLE
newrelic_one_dashboard failing to apply due to 502 Bad Gateway

### ISSUE THREAD

**Issue by rsdoherty** [newrelic/terraform-provider-newrelic#2477] opened 2023-10-03 09:00 UTC
## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version

```
➜ ~  terraform -v       
Terraform v1.5.7
on windows_amd64
```

### Affected Resource(s)

- `newrelic_one_dashboard`

### Terraform Configuration

```hcl
terraform {
  required_providers {
    newrelic = {
      source = "newrelic/newrelic"
    }
  }
}

resource "newrelic_one_dashboard" "dashboard" {
  name        = "Test Dashboard"
  permissions = "public_read_only"
  dynamic "page" {
    for_each = [
      var.my_example_dashboard,
    ]
    content {
      name = page.value["name"]
      dynamic "widget_area" {
        for_each = page.value["widget_area"]
        content {
          title  = widget_area.value["title"]
          row    = widget_area.value["row"]
          column = widget_area.value["column"]
          height = widget_area.value["height"]
          width  = widget_area.value["width"]
          nrql_query {
            query = widget_area.value["nrql_query"]
          }
        }
      }
      dynamic "widget_bar" {
        for_each = page.value["widget_bar"]
        content {
          title  = widget_bar.value["title"]
          row    = widget_bar.value["row"]
          column = widget_bar.value["column"]
          height = widget_bar.value["height"]
          width  = widget_bar.value["width"]
          nrql_query {
            query = widget_bar.value["nrql_query"]
          }
        }
      }
      dynamic "widget_billboard" {
        for_each = page.value["widget_billboard"]
        content {
          title  = widget_billboard.value["title"]
          row    = widget_billboard.value["row"]
          column = widget_billboard.value["column"]
          height = widget_billboard.value["height"]
          width  = widget_billboard.value["width"]
          nrql_query {
            query = widget_billboard.value["nrql_query"]
          }
        }
      }
      dynamic "widget_line" {
        for_each = page.value["widget_line"]
        content {
          title  = widget_line.value["title"]
          row    = widget_line.value["row"]
          column = widget_line.value["column"]
          height = widget_line.value["height"]
          width  = widget_line.value["width"]
          nrql_query {
            query = widget_line.value["nrql_query"]
          }
          dynamic "units" {
            for_each = widget_line.value["unit"] != null ? [1] : []
            content {
              unit = widget_line.value["unit"]
            }
          }
        }
      }
      dynamic "widget_pie" {
        for_each = page.value["widget_pie"]
        content {
          title  = widget_pie.value["title"]
          row    = widget_pie.value["row"]
          column = widget_pie.value["column"]
          height = widget_pie.value["height"]
          width  = widget_pie.value["width"]
          nrql_query {
            query = widget_pie.value["nrql_query"]
          }
        }
      }
      dynamic "widget_table" {
        for_each = page.value["widget_table"]
        content {
          title  = widget_table.value["title"]
          row    = widget_table.value["row"]
          column = widget_table.value["column"]
          height = widget_table.value["height"]
          width  = widget_table.value["width"]
          nrql_query {
            query = widget_table.value["nrql_query"]
          }
        }
      }
    }
  }
}

variable "my_example_dashboard" {
  description = "Test Dashboard - Terraform"
  default = {
    name        = "Test Dashboard - Terraform"
    widget_area = []
    widget_bar = []
    widget_billboard = []
    widget_line      = []
    widget_pie       = []
    widget_table     = []
  }
  type = object({
    name = string
    widget_area = list(object({
      column     = number
      height     = number
      row        = number
      title      = string
      width      = number
      nrql_query = string
    }))
    widget_bar = list(object({
      column     = number
      height     = number
      row        = number
      title      = string
      width      = number
      nrql_query = string
    }))
    widget_billboard = list(object({
      column     = number
      height     = number
      row        = number
      title      = string
      width      = number
      nrql_query = string
    }))
    widget_line = list(object({
      column     = number
      height     = number
      row        = number
      title      = string
      width      = number
      nrql_query = string
      unit       = optional(string)
    }))
    widget_pie = list(object({
      column     = number
      height     = number
      row        = number
      title      = string
      width      = number
      nrql_query = string
    }))
    widget_table = list(object({
      column     = number
      height     = number
      row        = number
      title      = string
      width      = number
      nrql_query = string
    }))
  })
}
```

### Actual Behavior

```
module.x.newrelic_one_dashboard.dashboard: Modifying... [id=MTE1MDQwNXxWSVp8REFTSEJPQVJEfGRhOjMyMjQzNzM]
module.x.newrelic_one_dashboard.dashboard: Still modifying... [id=MTE1MDQwNXxWSVp8REFTSEJPQVJEfGRhOjMyMjQzNzM, 10s elapsed]
╷
│ Error: maximum retries reached: Operation on dashboard entity failed with guid:MTE1MDQwNXxWSVp8REFTSEJPQVJEfGRhOjMyMjQzNzM with cause: Error 502 calling Insights with url https://insights-api.service.nr-ops.net/rpm_api/1/accounts/<account>/collections: upstream connect error or disconnect/reset before headers. reset reason: protocol error
```

### Expected Behavior

- Apply completes without issues

### Steps to Reproduce

1. `terraform apply`

### Debug Output

I'm hesitant to provide the *full* debug output in a gist on public GitHub as it has things like my corporate API keys against our account, so I've extracted the relevant information but happy to provide further details in a support ticket if needed:

https://gist.github.com/rsdoherty/7b94c9d03946128d79492a6eb10d109d

### Panic Output

N/A

### Important Factoids

N/A

### References

N/A

**Comment by pranav-new-relic** [comment] 2023-10-03 09:16
Hi @rsdoherty, we've seen that the error message you've attached usually indicates a user permissions issue (when a dashboard is created/updated from an account with incorrect access specifications). Can you please share your account ID (probably, the full debug logs would have that anyway, so you can consider mailing the full debug logs) to pnandula@newrelic.com? We'll be able to reach out to the right team at New Relic that would help get to the cause of this. Thanks!

**Comment by rsdoherty** [comment] 2023-10-03 09:27
Thanks for the quick response!

I have followed up via email with our account ID, as well as specfic user ID's that are experiencing the issue.

Regards,
Ryan

**Comment by pranav-new-relic** [comment] 2023-10-03 09:30
Received your mail - thanks! I'll try to reach out to the right team here at New Relic - will post back when I hear back from them. Thanks!

**Comment by pranav-new-relic** [comment] 2023-10-03 11:21
@rsdoherty - closing this issue as we shall be shifting to a different communication channel for this, given that it has been clarified that this is a user permissions issue. Thanks!

**Closed by pranav-new-relic** 2023-10-03 11:21 UTC
