### ISSUE TITLE
filter_current_dashboard of newrelic_one_dashboard is not handled properly

### ISSUE THREAD

**Issue by dvishniakov** [newrelic/terraform-provider-newrelic#1494] opened 2021-10-26 04:53 UTC
## Please include the following with your bug report

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
1.0.9

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_one_dashboard `
- `one_dashboard_raw` (according to #1413 )

### Terraform Configuration
Any basic config of newrelic_one_dashboard with widget_table and filter_current_dashboard=true

### Actual Behavior
Terraform plan and apply operations show changes every time:
```
      ~ page {
...
          ~ widget_table {
              ~ filter_current_dashboard = false -> true
```
### Expected Behavior
no changes

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` or `terraform plan` (after apply)

**Comment by achupryn** [comment] 2021-12-06 16:23
The issue is still present in v2.33.0
```
$terraform -version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.33.0
```

**Comment by joshua-paypay** [comment] 2022-01-05 02:34
## Issue
Hi, this is still not working correctly in 2.34.1.

```
$ terraform -version
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.34.1
```

I had some issue setting up dashboards originated from a json file copy from an old dashboard.
The original dashboard had `linked_entity_guids = []` to the old dashboard.

```
widget_bar {
  # omitting details
  linked_entity_guids = ["old-dashboard-guid"]
}
```
This works fine, however, it is pointing to the old dashboard.

So, I've changed the config to 
```
widget_bar {
  # omitting details
  filter_current_dashboard = true
}
```

The dashboard still points to the old one.

## Experiments
I did some experiments
1. I created a dashboard like my real dashboard (business details omitted). Then both work fine. Widget 1 can filter the test dashboard.
```
resource "newrelic_one_dashboard" "test-dashboard" {

  page {
    widget_bar {
      name = "widget 1"
      filter_current_dashboard =  true
    }

    widget_bar {
       name = "widget 2"
      linked_entity_guids = ["old-dashboard-guid"]
    }
  }
}
```
2. I removed the guids from widget 2. Then Widget 2 had no filters. This is also fine.
```
resource "newrelic_one_dashboard" "test-dashboard" {

  page {
    widget_bar {
      name = "widget 1"
      filter_current_dashboard =  true
    }

    widget_bar {
       name = "widget 2"
      linked_entity_guids = []
    }
  }
}
3. I add `filter_current_dashbaord = true` to widget 2. However **no filter is generated**.
```
resource "newrelic_one_dashboard" "test-dashboard" {

  page {
    widget_bar {
      name = "widget 1"
      filter_current_dashboard =  true
    }

    widget_bar {
       name = "widget 2"
      linked_entity_guids = []
    }
  }
}
```
![Screen Shot 2022-01-05 at 11 26 26](https://user-images.githubusercontent.com/91855917/148151616-8c9b23e5-db6a-4706-873b-284ee388e14e.png)

**Comment by MrColeC** [comment] 2022-01-25 22:21
We are having the same issue.

More data:
- I found on a fresh Dashboard creation, the feature works and the filtering is possible
- However on subsequent Terraform applies the filtering can be removed from the widgets and it is not possible to add it back via TF without tainting the entire dashboards state and executing a complete destroy/create
- Adding the toggle in the UI (filter current dashboard UI toggle in New Relic's UI for that dashboard) does not reflect or show up as a state change for this item

**Comment by zeffron** [comment] 2022-01-25 22:40
@joshua-paypay and @MrColeC your issue sounds like a separate issue from the one the original post was about. Could you maybe open a second issue to track that?
@dvishniakov Could you maybe adjust the title of this issue to be more specific to the plan showing changes every time?

**Comment by MrColeC** [comment] 2022-01-25 22:46
The experience I have is the same as what is reported:
```
Actual Behavior
Terraform plan and apply operations show changes every time:

      ~ page {
...
          ~ widget_table {
              ~ filter_current_dashboard = false -> true
```
Even though the state of the dashboard is unchanged, and terraform applied successfully, subsequent back-to-back TF runs express that the value needs to change from `false` to `true` (but never do). Thus, the feature does not work; "filter_current_dashboard of newrelic_one_dashboard is not handled properly".

**Comment by zeffron** [comment] 2022-01-25 23:17
@MrColeC The plan you have is the same as what's reported. Your expected behavior is different. In your case, you expect those changes to be there, and for those changes to then be applied. In the reported issue, the expected behavior is for those changes to _not_ be there, as they were applied previously.

**Comment by MrColeC** [comment] 2022-01-25 23:26
Sorry I am being confusing. Thank you for discussing this.
I do not expect those changes to be there.

1. We try to use this feature (filter_current_dashboard)
2. It creates the dashboard, and it works as expected in the UI (yay!)
3. I immediately run the same TF apply (I do not change any TF) and it says that it has not made the state updates, and `filter_current_dashboard` is false and needs to be true (not good)

The TF state and the New Relic UI are not in sync.
Further, updates to a widget that is working will "break" the filtering and it cannot be added back using this same TF, which is confusing.

**Comment by zeffron** [comment] 2022-01-26 01:07
@MrColeC Gotcha, thank you for clarifying. It sounds like you have two (possibly related) issues then.
1. The one this one was opened for, which is the inaccurate indication of needing to (re)apply `filter_current_dashboard`
2. Updates to the widget can cause descync between reality and Terraform management.

Can you elaborate on what updates you've seen this desync with? Are these changes made to the widget via the UI? Or changes made with Terraform?

**Comment by joshua-paypay** [comment] 2022-01-26 02:25
@zeffron https://github.com/newrelic/terraform-provider-newrelic/issues/1604 new issue created

**Comment by MrColeC** [comment] 2022-01-27 20:20
Context:
I write TF to create a dashboard, using the following Terraform.
```
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = ">= 2.35.1"
    }
  }
}

provider "newrelic" {
  account_id = "<redacted>"
  region     = "US"
}

resource "newrelic_one_dashboard" "default" {
  name        = "Ticket 1494"
  description = "Managed via Terraform"

  # Build out all dashboard pages (our default page1 and anything else configured
  page {
    name        = "Simple Page"
    description = "Simple Page"

    # Pie charts
    widget_pie {
      title                    = "Filter Example"
      row                      = 1
      column                   = 1
      width                    = 5
      height                   = 5
      linked_entity_guids      = null
      filter_current_dashboard = true
      nrql_query {
        query = "FROM K8sClusterSample select uniqueCount(hostname) FACET clusterName limit max since 5 minutes ago"
      }
    }

    widget_pie {
      title                    = "Target Example"
      row                      = 1
      column                   = 6
      width                    = 7
      height                   = 5
      linked_entity_guids      = null
      filter_current_dashboard = false
      nrql_query {
        query = "FROM K8sClusterSample select uniqueCount(hostname) FACET instanceType limit max since 5 minutes ago"
      }
    }
  }
}
```

Results: 
After an apply, run a TF plan and it says it needs to still set the filter to true. Which is not true. 
Further, if you use TF to edit that pie chart, the filter function will "drop" and you cannot use TF to add it back.
Additionally, if you toggle on that it _is_ filtering (via the web UI) the TF state refresh will not detect it.

Result details:
```
terraform plan
newrelic_one_dashboard.default: Refreshing state... [id=<redacted>]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # newrelic_one_dashboard.default will be updated in-place
  ~ resource "newrelic_one_dashboard" "default" {
        id          = "<redacted>"
        name        = "Ticket 1494"
        # (5 unchanged attributes hidden)

      ~ page {
            name        = "Simple Page"
            # (2 unchanged attributes hidden)

          ~ widget_pie {
              ~ filter_current_dashboard = false -> true
                id                       = "<redacted>"
                # (6 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }
            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

**Comment by MrColeC** [comment] 2022-01-27 20:21
Does this help @zeffron ?
Sorry for the delay in response.

**Comment by zeffron** [comment] 2022-01-27 22:18
@MrColeC Yes, thank you!

**Comment by rdhar** [comment] 2022-01-30 05:48
While re-trying #1413, I came across a li'l tidbit that might help address this issue (i.e., unnecessary noise in the execution logs) with an interim solution: leveraging `ignore_changes` from Terraform's [`lifecycle` meta-argument docs](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes).

```tf
resource "newrelic_one_dashboard" "the_dashboard" {
  lifecycle {
    ignore_changes = [page["filter_current_dashboard"]]
  }
  name = "The Dashboard"
  …
```

This will suppress redundant noise from `filter_current_dashboard` on subsequent updates. Almost goes without saying, the ideal solution here would be for the provider to properly register the value of the boolean, but this isn't too shabby a workaround.

**Comment by MrColeC** [comment] 2022-01-31 03:15
Support for Lifecycle only exists on Resources, not Dynamic blocks. As the nature of a Dashboard can be complex at times and most have multiple pages and widgets, Dynamics are generally used.

https://github.com/hashicorp/terraform/issues/24188

I agree this helps the example, but for us it is not going to help in production.

**Comment by rdhar** [comment] 2022-03-01 22:57
Hey @dvishniakov & @MrColeC, could you retry your use-cases?

Following the release of [v2.38.0 ](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.38.0), I've found it addressed some issues relating to dashboard filters.

**Comment by MrColeC** [comment] 2022-03-02 22:00
@rdhar I do see in some limited use cases, or base case deployments with no follow on updates, it is functional. However, at scale and on updates, I still see issues. I think the issue persists.

I looked over the PR's merged in that made up [v2.38.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.38.0) and I didn't see any changes I would think are associated with this issue.

**Closed** 2022-03-15 16:15 UTC
Labels: bug, group-dashboards

**Comment by MrColeC** [comment] 2022-03-15 18:15
@mbazhlekova our testing and our use cases all seem to work with this. This is a full solution and we see no side effects. Nice!

**Comment by zeffron** [comment] 2022-03-15 18:23
Can confirm the beta seems to work for our use case as well.

**Comment by mbazhlekova** [comment] 2022-03-16 15:01
@MrColeC We intentionally don't allow `linked_entity_guids` and `filter_current_dashboard` to both be set. Since they both set the `linked_entity_guids` field, it can lead to conflicts. Are you seeing this error in another use case?

**Comment by zeffron** [comment] 2022-03-16 16:33
@MrColeC Depending on Terraform version, I think it can tell the difference between something explicitly set to `null`, and something not set. Does it still reproduce if you delete the lines with the unused one (`filter_current_dashboard` when it's set to `false`, and `linked_entity_guids` when filter is true)?

**Comment by zeffron** [comment] 2022-03-16 17:12
Ah, yes, I missed the change to the NRQL statement initially. I am able to reproduce the same failure.

**Comment by mbazhlekova** [comment] 2022-03-16 17:57
@MrColeC I see, thanks for the clarification! Looks like we need to refine the logic a bit to get it to work properly.

**Comment by mbazhlekova** [comment] 2022-03-17 16:40
@MrColeC @zeffron We rolled out another release - [v2.41.0-beta.2](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.41.0-beta.2) with a fix for the `linked_entity_guids` error. Please let us know if this resolves the issues you're seeing.

**Comment by zeffron** [comment] 2022-03-17 17:21
v2.41.0-beta.2 does seem to have resolved the issue for me.

**Comment by MrColeC** [comment] 2022-03-17 18:22
I agree with @zeffron 
@mbazhlekova this has fixed it for me and I have not found any edge cases. Thank you for fixing this!
