### ISSUE TITLE
Resource created before being fully destroyed after renaming

### ISSUE THREAD

**Issue by rubentsirunyan** [newrelic/terraform-provider-newrelic#1268] opened 2021-03-31 06:56 UTC
When renaming the `newrelic_synthetics_monitor` resource and running `terraform apply`, it fails with the following error:
```
Error: 400 response returned: Invalid name specified: 'TEST'; a monitor with that name already exists.
```
Looks like the old monitor is not fully deleted by the time terraform tries to create a new one.

This is the initial terraform code for the resource:
```hcl
resource "newrelic_synthetics_monitor" "foo" {
  name      = "TEST"
  type      = "SIMPLE"
  frequency = 5
  status    = "ENABLED"
  locations = ["AWS_US_EAST_1", "AWS_US_EAST_2"]

  uri               = "https://example.com"
  validation_string = "add example validation check here"
  verify_ssl        = true
}
```
and this is the same resource after renaming it:
```hcl
resource "newrelic_synthetics_monitor" "bar" {
  name      = "TEST"
  type      = "SIMPLE"
  frequency = 5
  status    = "ENABLED"
  locations = ["AWS_US_EAST_1", "AWS_US_EAST_2"]

  uri               = "https://example.com"
  validation_string = "add example validation check here"
  verify_ssl        = true
}
```

Here is the plan output after renaming the resource:
```
newrelic_synthetics_monitor.foo: Refreshing state... [id=b6c4bea5-23f6-466b-9774-dd0b797abe2e]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # newrelic_synthetics_monitor.bar will be created
  + resource "newrelic_synthetics_monitor" "bar" {
      + frequency         = 5
      + id                = (known after apply)
      + locations         = [
          + "AWS_US_EAST_1",
          + "AWS_US_EAST_2",
        ]
      + name              = "TEST"
      + sla_threshold     = 7
      + status            = "ENABLED"
      + type              = "SIMPLE"
      + uri               = "https://example.com"
      + validation_string = "add example validation check here"
      + verify_ssl        = true
    }

  # newrelic_synthetics_monitor.foo will be destroyed
  - resource "newrelic_synthetics_monitor" "foo" {
      - bypass_head_request       = false -> null
      - frequency                 = 5 -> null
      - id                        = "b6c4bea5-23f6-466b-9774-dd0b797abe2e" -> null
      - locations                 = [
          - "AWS_US_EAST_1",
          - "AWS_US_EAST_2",
        ] -> null
      - name                      = "TEST" -> null
      - sla_threshold             = 7 -> null
      - status                    = "ENABLED" -> null
      - treat_redirect_as_failure = false -> null
      - type                      = "SIMPLE" -> null
      - uri                       = "https://example.com" -> null
      - validation_string         = "add example validation check here" -> null
      - verify_ssl                = true -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/newrelic/newrelic v2.14.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_monitor`

### Terraform Configuration
```hcl
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.13"
    }
  }
}
```

### Actual Behavior
Terraform destroys the old resource but fails to create the new one with the following error message:
```
Error: 400 response returned: Invalid name specified: 'TEST'; a monitor with that name already exists.
```

### Expected Behavior
Terraform should have successfully destroyed the old resource and create the new one.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `newrelic_synthetics_monitor` resource.
2. Rename the resource and run `terraform apply`

### Debug Output
https://gist.github.com/rubentsirunyan/bfb38540fe997109b9e922b209d328b9

**Comment by kidk** [comment] 2022-08-01 16:52
Duplicate of #1693

**Closed by kidk** 2022-08-01 16:52 UTC
Labels: bug
