### ISSUE TITLE
The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled upgrading to 3.11.0 - The terraform-provider-newrelic_v3.11.0 plugin crashed!

### ISSUE THREAD

**Issue by nvbannam** [newrelic/terraform-provider-newrelic#2178] opened 2022-12-23 06:10 UTC
Hi there,

I am having an issue when I run terraform plan while upgrading the version from v2.37.0 to v3.11.0

Here is the full trace log - [run-fkcgReUUj1yVNwi9-plan-log.txt](https://github.com/newrelic/terraform-provider-newrelic/files/10297354/run-fkcgReUUj1yVNwi9-plan-log.txt)

![image](https://user-images.githubusercontent.com/113460994/209279627-529a377a-5dde-4521-a600-db92e5160450.png)

![image](https://user-images.githubusercontent.com/113460994/209279788-d850e399-e22f-44f8-bedc-f57425da3a1c.png)

local:
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.11.0

Terraform v1.2.5
on linux_amd64
provider registry.terraform.io/newrelic/newrelic v3.11.0

**config:**
`resource "newrelic_nrql_alert_condition" "Records_Kafka_Lag_infrastructure_alert_condition" {
  policy_id                    = newrelic_alert_policy.noc_infrastructure.id
  type                         = "static"
  name                         = "Records - Lag"
  description                  = "Alert when lags are taking too long to catch up"
  enabled                      = true
  violation_time_limit_seconds = 3600

  fill_option = "none"

  aggregation_window             = 300
  expiration_duration            = 120
  open_violation_on_expiration   = false
  close_violations_on_expiration = false

  nrql {
    query = "SELECT latest(redacted as it contains sensitive info)"
  }

  critical {
    operator              = "above"
    threshold             = 500
    threshold_duration    = 600
    threshold_occurrences = "ALL"
  }
}`

steps required to reproduce the issue, for example:
upgrade version from 2.37.0 to 3.11.0
updated the code to 3.11.0 standards
Ran into no schema available for modules, fixed it.
and when I run terraform plan, now the plan is failing with the below error

The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled
![image](https://user-images.githubusercontent.com/113460994/209279788-d850e399-e22f-44f8-bedc-f57425da3a1c.png)

**Comment by sanderblue** [comment] 2023-02-03 20:43
@nvbannam this error looks like it's coming from your resource `newrelic_one_dashboard`. Can you share the config for that resource please?

**Comment by nvbannam** [comment] 2023-02-08 23:44
[TerraformProvider.zip](https://github.com/newrelic/terraform-provider-newrelic/files/10690956/TerraformProvider.zip)
@sanderblue attached are the config we have, please let me know if you need more information.

**Comment by sanderblue** [comment] 2023-02-13 15:34
@nvbannam, can you reproduce this error in the latest version (**v3.14.0**) of the provider? It looks like a fix for this might have been released already. Please give that a try and let us know if the bug still exists 🙂

**Comment by NSSPKrishna** [comment] 2023-02-27 11:26
”We haven’t heard back from you in a long time so we will close the ticket. If you feel this is still a valid request or bug, feel free to create a new issue.”

**Closed by NSSPKrishna** 2023-02-27 11:26 UTC
Labels: bug, waiting-response
