### ISSUE TITLE
Create a resource for browser applications

### ISSUE THREAD

**Issue by ctrombley** [newrelic/terraform-provider-newrelic#309] opened 2020-01-14 18:15 UTC
The APIs are available to provision browser applications, so we should build around these endpoints in the provider.

**Comment by jthurman42** [comment] 2020-02-18 22:58
Requires resolution of upstream issue newrelic/newrelic-client-go#135 to complete

**Comment by ctrombley** [comment] 2020-06-17 18:46
The data source requirement is now supported via the `newrelic_entity` data source.  The name of this ticket has been updated to reflect this.

Work will still be required to provision new browser applications.

**Comment by jthurman42** [comment] 2021-03-02 21:45
Duplicate of #73

**Closed by jthurman42** 2021-03-02 21:45 UTC
Labels: dependencies, enhancement, new-resource
