### ISSUE TITLE
Policy with ID xxxx not found: BAD_USER_INPUT. Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by yuklia** [newrelic/terraform-provider-newrelic#2071] opened 2022-10-25 13:43 UTC
# Problem: 
## 2 Error: Provider produced inconsistent result after apply 
But in fact policy is present both in NewRelic dashboard and Terraform state
---
- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
```
Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.36.1
+ provider registry.terraform.io/newrelic/newrelic v2.48.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_nrql_alert_condition`
- `newrelic_alert_policy`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Here is my Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
# versions.tf
terraform {
  required_version = ">= 1.2"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.5.2"
    }
  }
}
---
# module: policy_generator

# main.tf
resource "newrelic_alert_policy" "group_by_environments_type" {
  name                = "alerts_conditions_${replace(var.environment_type, "-", "_")}_environments"
  incident_preference = var.incident_preference
}

# outputs.tf
output "policy" {
  value = newrelic_alert_policy.group_by_environments_type
}

# variables.tf
# incident_preference :
# PER_POLICY - Only one open incident at a time for this alert policy.
# PER_CONDITION - Only one open incident at a time per alert condition.
# PER_CONDITION_AND_TARGET - Open an incident every time a condition is violated.

variable "incident_preference" {
  type        = string
  description = "https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/alert_policy#incident_preference"
  default     = "PER_POLICY"

  validation {
    condition     = contains(["PER_POLICY", "PER_CONDITION", "PER_CONDITION_AND_TARGET"], var.incident_preference)
    error_message = "Must be `PER_POLICY`, `PER_CONDITION`, `PER_CONDITION_AND_TARGET`."
  }
}

variable "environment_type" {
  type        = string
  description = ""

  validation {
    condition     = contains(["internal", "production", "non-production"], var.environment_type)
    error_message = "Must be `internal`, `production`, `non-production`."
  }
}

----
# module: conditons

# main.tf
module "policies" {
  source = "../policy_generator"

  environment_type = var.environment_type
  incident_preference = "PER_CONDITION_AND_TARGET"
}

locals {
  filtered_map = {
    for k, v in var.settings : k => v[var.environment_type]
    if contains(keys(v), var.environment_type) && try(length(v[var.environment_type]), 0) != 0
  }
}

resource "newrelic_nrql_alert_condition" "alerts" {
  for_each           = local.filtered_map
  policy_id          = module.policies.policy.id
  name               = each.value.name
  description        = try(each.value.description, each.value.name)
  type               = try(each.value.type, "static")
  enabled            = try(each.value.enabled, true)
  aggregation_window = try(each.value.aggregation_window, 60)
  aggregation_method = try(each.value.aggregation_method, "event_flow")
  aggregation_delay  = try(each.value.aggregation_delay, 120)
  baseline_direction = try(each.value.baseline_direction, null)

  violation_time_limit_seconds = 8 * 60 * 60
  expiration_duration          = try(each.value.expiration_duration, null)
  open_violation_on_expiration = try(each.value.open_violation_on_expiration, null)

  nrql {
    query = each.value.query
  }

  critical {
    operator              = each.value.critical.operator
    threshold             = each.value.critical.threshold
    threshold_duration    = try(each.value.critical.threshold_duration, 60)
    threshold_occurrences = try(each.value.critical.threshold_occurrences, "all")
  }

  dynamic "warning" {
    for_each = try(length(each.value.warning), 0) > 0 ? [each.value.warning] : []
    content {
      operator              = warning.value.operator
      threshold             = warning.value.threshold
      threshold_duration    = try(warning.value.threshold_duration, 60)
      threshold_occurrences = try(warning.value.threshold_occurrences, "all")
    }
  }
}
# variables.tf
variable "environment_type" {
  type        = string
  description = ""

  validation {
    condition     = contains(["internal", "production", "non-production"], var.environment_type)
    error_message = "Must be `internal`, `production`, `non-production`."
  }
}

variable "settings" {
  type = any
}
# versions.tf
terraform {
  required_version = ">= 1.2"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.5.2"
    }
  }
}

```

### Actual Behavior
```
module.alerts.module.production_conditions.module.policies.newrelic_alert_policy.group_by_environments_type: Creating...
module.alerts.module.production_conditions.module.policies.newrelic_alert_policy.group_by_environments_type: Creation complete after 1s [id=3668900]
module.alerts.module.production_conditions.newrelic_nrql_alert_condition.alerts["heathy_hosts_in_target_group"]: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.alerts.module.production_conditions.newrelic_nrql_alert_condition.alerts["heathy_hosts_in_target_group"], provider
│ "provider[\"registry.terraform.io/newrelic/newrelic\"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
### Expected Behavior
When I run `terraform apply`,  I see planned changes and after approve it should go smoothly
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # module.alerts.module.production_conditions.newrelic_nrql_alert_condition.alerts["heathy_hosts_in_target_group"] will be created
  + resource "newrelic_nrql_alert_condition" "alerts" {
      + account_id                   = (known after apply)
      + aggregation_delay            = "120"
      + aggregation_method           = "event_flow"
      + aggregation_window           = 60
      + description                  = "P1 No Healthy Hosts in Target Group"
      + enabled                      = true
      + entity_guid                  = (known after apply)
      + id                           = (known after apply)
      + name                         = "P1 No Healthy Hosts in Target Group"
      + policy_id                    = (known after apply)
      + type                         = "static"
      + violation_time_limit         = (known after apply)
      + violation_time_limit_seconds = 28800

      + critical {
          + operator              = "below_or_equals"
          + threshold             = 0
          + threshold_duration    = 600
          + threshold_occurrences = "all"
        }

      + nrql {
          + query = "SELECT min(provider.healthyHostCount.Minimum) - max(provider.unHealthyHostCount.Maximum) FROM LoadBalancerSample WHERE provider in ('AlbTargetGroup','NlbTargetGroup') AND label.details like '%-pr%' FACET label.details"
        }
    }

  # module.alerts.module.production_conditions.module.policies.newrelic_alert_policy.group_by_environments_type will be created
  + resource "newrelic_alert_policy" "group_by_environments_type" {
      + account_id          = (known after apply)
      + id                  = (known after apply)
      + incident_preference = "PER_CONDITION_AND_TARGET"
      + name                = "alerts_conditions_production_environments"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + alerts_settings = {
      + elasticsearch_cluster_status_red = {
          + internal       = {}
          + non-production = {
              + aggregation_window = 60
              + critical           = {
                  + operator           = "above"
                  + threshold          = 1
                  + threshold_duration = 900
                }
              + description        = "P1 Elasticsearch Cluster Status RED"
              + enabled            = true
              + name               = "P1 Elasticsearch Cluster Status RED"
              + query              = "SELECT average(aws.es.ClusterStatus.red) FROM Metric WHERE tags.Name not like '%-pr%' FACET tags.Name"
              + warning            = {
                  + operator           = "above"
                  + threshold          = 1
                  + threshold_duration = 600
                }
            }
          + production     = {}
        }
      + heathy_hosts_in_target_group     = {
          + internal       = {}
          + non-production = {}
          + production     = {
              + aggregation_window = 60
              + critical           = {
                  + operator           = "below_or_equals"
                  + threshold          = 0
                  + threshold_duration = 600
                }
              + description        = "P1 No Healthy Hosts in Target Group"
              + enabled            = true
              + name               = "P1 No Healthy Hosts in Target Group"
              + query              = "SELECT min(provider.healthyHostCount.Minimum) - max(provider.unHealthyHostCount.Maximum) FROM LoadBalancerSample WHERE provider in ('AlbTargetGroup','NlbTargetGroup') AND label.details like '%-pr%' FACET label.details"
            }
        }
    }
  + debug           = {
      + is_apm                     = false
      + is_infrastructure          = true
      + is_infrastructure_customer = false
      + is_infrastructure_internal = true
    }

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```

### Steps to Reproduce
1. `terraform apply`

### Debug Output
https://gist.github.com/yuklia/bd52005f1c679122c10278e5c85c1155

### Panic Output
-

### Important Factoids
The error says that **ID 3668990 not found** but as you can see on the picture below it is exists **in NewRelic system.** 
⬇️ 
```
 Error: Policy with ID 3668990 not found: BAD_USER_INPUT
│ 
│   with module.alerts.module.production_conditions.newrelic_nrql_alert_condition.alerts["heathy_hosts_in_target_group"],
│   on alerts/conditions/main.tf line 15, in resource "newrelic_nrql_alert_condition" "alerts":
│   15: resource "newrelic_nrql_alert_condition" "alerts" {
```

Also I see that this policy exists in Terraform state
```
# module.alerts.module.production_conditions.module.policies.newrelic_alert_policy.group_by_environments_type:
resource "newrelic_alert_policy" "group_by_environments_type" {
    account_id          = REDACTED
    id                  = "3668990"
    incident_preference = "PER_CONDITION_AND_TARGET"
    name                = "alerts_conditions_production_environments"
}
```
![image](https://user-images.githubusercontent.com/4895059/197787394-3ca010ce-fd4a-44e4-9859-367ff391663c.png)

**Comment by kidk** [comment] 2022-10-27 13:27
Thanks @yuklia for the detailed report. We've been able to create a theory on why this is happening. We're going to prioritise implementing a fix.

**Comment by kidk** [comment] 2022-11-15 07:44
We have a possible fix out with the latest provider v3.7.0. We changed our read mechanism to handle the API congestion.

I'm going to close this for now. Please reply if you experience the error again and I will reopen.

**Comment by JBallin** [comment] 2023-01-17 04:55
Seeing this on `3.12.0`.

**Comment by RavitejaSurampudi** [comment] 2023-01-17 06:49
@JBallin Thank you for bringing this to our notice. we are looking into it.

**Comment by pranav-new-relic** [comment] 2023-03-27 13:48
Hi @JBallin, @doryphores - we've tried reproducing an issue, almost similar to this (#2157), to which I've added [this comment](https://github.com/newrelic/terraform-provider-newrelic/issues/2157#issuecomment-1485104364). In short, we haven't been able to reproduce this issue, with a couple of tests aimed at creating resources similar to the ones in the Terraform configuration of this issue. Can you please have a look at the comment, and let us know if you still see the issue? Thanks!

**Comment by JBallin** [comment] 2023-03-27 15:56
@pranav-new-relic I don't have time to dig into reproducing, but I can share a couple thoughts:

1. It doesn't happen every time, as you alluded to (API latency) it's a race condition where the policy should've been created already but it wasn't for some reason.
2. IMO the issue is that resources that rely on policy are not waiting for it to be successfully created before applying themselves. Maybe you can check this logic.

Thanks!

**Comment by pranav-new-relic** [comment] 2023-03-27 16:59
@JBallin thanks for sharing - we'll take a look.

**Comment by pranav-new-relic** [comment] 2023-04-13 06:20
Hi everyone - we've taken a look at the underlying logic, and the API team has also looked into the same. We find that the issue with API latency seems to no longer exist, and things are working as expected with the latest version of the Terraform Provider. We'd like to close this issue for now as it's been around for a really long time, and does not seem to recur at the moment. Please feel free to create a new issue if you find similar behaviour again - thanks.

**Closed by pranav-new-relic** 2023-04-13 06:20 UTC
Labels: bug

**Comment by neilfordyce** [comment] 2023-04-19 17:07
We came across this same issue twice today with version v3.20.2 today at around 2023-04-19 12:44 UTC. Both case were creating a new policy and several condition in the same `terraform apply` and end up getting a `Error: Policy with ID xxx not found: BAD_USER_INPUT` when applying.  Both cases were fixed by rerunning terraform apply, so we've got a reasonable workaround, but it does still seem flaky.  It isn't happening very often, but it does lead to confusion. 

Maybe polling for the existence of an alert policy after creating one, or even just adding some delay in after creating alert policy would be enough?

**Comment by tomaszkrawczyk-dealsumm** [comment] 2024-02-01 12:01
Why this issue is closed, it's happening still. I've got the same results on my site when trying to apply such code:
```

resource "newrelic_alert_policy" "django_alert_policy" {
  name                = "Django alert policy"
  incident_preference = "PER_CONDITION"
}

resource "newrelic_nrql_alert_condition" "alert_condition_django_apdex" {
  account_id = XXX
  policy_id  = newrelic_alert_policy.django_alert_policy.id
  type       = "static"
  name       = "Apdex Score"

  description = <<-EOT
  This alert is triggered when the Apdex score is below 0.5 for 5 minutes
  EOT

  enabled                      = true
  violation_time_limit_seconds = 86400

  nrql {
    query = "SELECT apdex(apm.service.apdex) as 'Apdex' FROM Metric WHERE appName like '%'"
  }

  critical {
    operator              = "below"
    threshold             = 0.5
    threshold_duration    = 300
    threshold_occurrences = "all"
  }
  fill_option        = "none"
  aggregation_window = 60
  aggregation_method = "event_flow"
  aggregation_delay  = 120
}
```
Logs:
```
Plan: 4 to add, 0 to change, 0 to destroy.
module.new_relic.newrelic_alert_policy.django_alert_policy: Creating...
module.new_relic.newrelic_alert_policy.django_alert_policy: Creation complete after 1s [id=5072299]
module.new_relic.newrelic_nrql_alert_condition.alert_condition_django_apdex: Creating...
╷
│ Error: Policy with ID 5072299 not found: BAD_USER_INPUT
│ 
│   with module.new_relic.newrelic_nrql_alert_condition.alert_condition_django_apdex,
│   on modules/new_relic/main.tf line 576, in resource "newrelic_nrql_alert_condition" "alert_condition_django_apdex":
│  576: resource "newrelic_nrql_alert_condition" "alert_condition_django_apdex" {
```

**Comment by irmiller22** [comment] 2024-04-10 13:28
Just ran into this error as well.

Error output after first apply attempt:

```
Error: DaqsServerError.CouldNotCheck: DAQS COULD_NOT_CHECK: COULD_NOT_CHECK: BAD_USER_INPUT

  with module.apm["pauth"].newrelic_nrql_alert_condition.apm_response_time[0],
  on ../../modules/default-alerts/apm/main.tf line 62, in resource "newrelic_nrql_alert_condition" "apm_response_time":
  62: resource "newrelic_nrql_alert_condition" "apm_response_time" {
```

The apply worked on the second attempt. It's clearly a bug that's still occurring, so I'm not sure why this was closed.

**Comment by alex-peresunko** [comment] 2024-07-12 13:23
HI, just ran into this error. Exactly the same behavior - policy exists in Newrelic but respective alerts cannot be created:

│ Error: Policy with ID 5460735 not found: BAD_USER_INPUT
│
│   with module.alerts-messageway.newrelic_nrql_alert_condition.alert_fc0c5308-6ff9-4d01-98ba-7e07d1a64f27,
│   on modules/alerts-messageway/alerts_static.tf.json line 33, in resource[0].newrelic_nrql_alert_condition.alert_fc0c5308-6ff9-4d01-98ba-7e07d1a64f27:
│   33:         }
