### ISSUE TITLE
Setting y_axis_left_min to 0 or null does not set the yAxisLeft to zero = true

### ISSUE THREAD

**Issue by OscarNeira** [newrelic/terraform-provider-newrelic#2324] opened 2023-04-10 07:42 UTC
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
3.20.1

### Affected Resource(s)
newrelic_one_dashboard

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our [GPG public key](https://github.com/newrelic/observability-as-code/blob/master/docs/developer-toolkit.asc).
# For more information on how to encrypt files check out the [GPG Privacy handbook](https://www.gnupg.org/gph/en/manual/x110.html).
```

### Actual Behavior
trying to migrate manual dashboards to terraform, the manual version set a value like this 
 "yAxisLeft": {
              "zero": true
            }

Using terraform cannot achieve the same result
tried set y_axis_left_min to 0 or null and still does not set zero true

### Expected Behavior
What should have happened?
y_axis_left_min = 0 or y_axis_left_min= null would set the widget yAxisLeft to  "zero": true

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a widget 
 widget_line {
      title  = "Publishing API Apdex"
      row    = 1
      column = 4
      height = 3
      width  = 3
      nrql_query {
        account_id = var.newrelic_account_id
        query      = <<EOT
SELECT apdex(apm.service.apdex) FROM Metric WHERE (appName='${var.app.test}') TIMESERIES FACET appName SINCE 24 hours ago
EOT
      }
      legend_enabled  = true
      y_axis_left_min = 0
      y_axis_left_max = 1
    }

2. terraform apply
3. New relic dashboard it does not start from 0
4. copy JSON to clipboard and as well, json object yAxisLeft missing
 "yAxisLeft": {
              "zero": true
            }

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by pranav-new-relic** [comment] 2023-04-10 15:39
Hi @OscarNeira - thanks for reporting this issue. Upon following the steps you've mentioned to reproduce this issue (using the same Terraform configuration), the following are my observations on the widget created - 

1. Upon copying the JSON version of the widget to the clipboard, the attribute ```"yAxisLeft": {"zero": true}``` does not exist. However, this exists when the same widget is created via the UI and not Terraform.
2. The widget created does seem to start from 0 and end and 1 (i.e. the range is the specified ```y_axis_left_min``` to ```y_axis_left_max```).

Though the widget created via Terraform does not have ```"yAxisLeft": {"zero": true}``` in its JSON version - the absence of this attribute does not change the minimum value of the left Y-Axis. As specified [here](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#nested-widget-blocks) in the docs, y_axis_left_min defaults to 0 even if it is not specified; hence, using ```y_axis_left_min = 0``` sets the lower bound of the Y-Axis of the widget to 0 (despite the JSON version of the widget shows no ```"yAxisLeft": {"zero": true}```) , as I've observed with the widget created upon reproducing this too.

Can you please re-check with the Terraform Configuration you've provided, and make sure the widget does not start from 0? We can possibly take a look at the absence of ```"zero" : true``` in the JSON, for consistency between UI created and Terraform created versions - however, the widget created via Terraform with ```y_axis_left_min=0``` is expected to start from zero. Please take a look and let us know. Thanks!

**Comment by OscarNeira** [comment] 2023-04-10 16:58
@pranav-new-relic , thanks for the quick response. Yes, the absence does not affect the minimum value of Y-Axis, the "yAxisLeft": {"zero": true} affect visually in the dashboard. In the attached image, you can notice on the left side (manual creation) that the apex and the count are displayed from 0, on the other side, on the terraform side, the min value continues to be zero, but the graph displays from the min value found.
![Screenshot 2023-04-10 at 19 42 56](https://user-images.githubusercontent.com/6389828/230949591-03410860-4092-41cf-b2de-1cca2cfb06d8.png)

The configuration from the documentation side is correct.  However, visually is different.

**Comment by pranav-new-relic** [comment] 2023-04-10 17:17
Hey @OscarNeira - thanks for the elaborate answer - really helps understand the issue well and guide us to the root cause. We shall take this fix up soon, based on priority - thanks!

**Comment by OscarNeira** [comment] 2023-04-10 17:38
Thanks

**Comment by pranav-new-relic** [comment] 2023-05-02 05:33
Hi @OscarNeira  - we have released a fix to this issue in the latest version of the Terraform Provider, [v3.21.3](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v3.21.3). A new argument has been added to the schema of `newrelic_one_dashboard` (in line widgets) called `y_axis_left_zero`, which would be a boolean value (true/false), about which you can read more in the updated documentation [here](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#widget_line). This argument would resemble the attribute `"zero"` in the JSON version of the line widget of the dashboard copied from the UI.

Few points about using this new argument -
- Using `y_axis_left_zero = false` would fit the graph to scale. However, if you specify values of  arguments `y_axis_left_min` and `y_axis_left_max` when `y_axis_left_zero = false`, it would override the nature of the graph to be fit to scale, and would eventually render values belonging to the range `y_axis_left_min` - `y_axis_left_max`. This is the case in the UI too - when you try creating a line widget and select "Fit to scale", but specify the minimum and maximum range of values, the fit to scale property is overridden. Hence, **if `y_axis_left_zero` is `false`, `y_axis_left_min` and `y_axis_left_max` are expected not to be specified.**
- Using `y_axis_left_zero = true` would render values in the graph starting from zero to the maximum, as is expected. If `y-axis_left_min` and `y_axis_left_max` are specified with `y_axis_left_zero = true`, values are rendered in the range of the specified minimum and maximum.
- `y_axis_left_zero` is an optional attribute, and would default to `false` if not specified, i.e. the graph would fit to scale unless `y_axis_left_zero = true` is added in the configuration.

Closing this issue as the fix is now live. Thanks for reporting!

**Closed by pranav-new-relic** 2023-05-02 05:33 UTC
Labels: bug

**Comment by OscarNeira** [comment] 2023-05-03 10:00
Hi @pranav-new-relic, I had some time to test this change today, and it is working as expected. Thanks for the fix.

**Comment by OscarNeira** [comment] 2023-05-29 07:36
Forgot to mention that it works fine
