### ISSUE TITLE
NRQL Alert Condition, [INTERNAL_SERVER_ERROR]

### ISSUE THREAD

**Issue by JPurcell1994** [newrelic/terraform-provider-newrelic#869] opened 2020-09-09 12:59 UTC
Hi there,

### Terraform Version
Terraform v0.12.29
provider.NewRelic v2.7.0

### Affected Resource(s)
newrelic_nrql_alert_condition

### Terraform Configuration Files
```
resource "newrelic_alert_policy" "cpu_policy" {
  name = "${var.app_name}-policy-tfnr"
}

resource "newrelic_nrql_alert_condition" "cpu_high_condition" {
  policy_id = newrelic_alert_policy.cpu_policy.id


  name        = "${var.app_name} cpu limit"
  type        = "static"
  runbook_url = var.runbook_url
  enabled     = true
  value_function       = "single_value"
  violation_time_limit = "ONE_HOUR"
  fill_option = "last_value"

  nrql {
    query             = "SELECT latest(cpuUsedCores / cpuLimitCores) * 100 WHERE containerName like '${var.app_name}' and clusterName like '${var.eks_cluster_name}' FROM K8sContainerSample"
    evaluation_offset = 3
  }

  critical {
    operator              = "above"
    threshold             = "90"
    threshold_duration    = 300
    threshold_occurrences = "ALL"
  }
}
```

### Debug Output
```
Error: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]
```

### Expected Behavior
An alert policy should be created, with an attached NRQL alert condition.

### Actual Behavior
An alert policy was created, but the nrql alert condition failed to build and returned the above error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by zlesnr** [comment] 2020-09-09 15:19
Thank you for reporting the issue.  With the HCL provided I'm able to reproduce.  We have one known issue that I expect to see a fix for this week, and that may clear this up.

**Comment by zlesnr** [comment] 2020-09-09 16:37
On second look, can you double check that NRQL query manually?  The errors here are leaving a bit to be desired, but this might be unrelated to the other issue I mentioned.

**Comment by JPurcell1994** [comment] 2020-09-10 08:18
Hi there,

It looks like you are right, unfortunately it seems to now be invalid NRQL, was there a change made to where things have to live in the query? This is simply a rebuild from an old dashboard/alert policy I used to make through terraform so wondering if I missed something in release notes. 

A query that works however is

```
"SELECT latest(cpuUsedCores / cpuLimitCores) * 100 FROM K8sContainerSample WHERE containerName like '${var.app_name}' and clusterName like '${var.eks_cluster_name}'"
```
Looks as if it now needs a from source before attaching any wheres to the NRQL.

Do you want me to leave it open as a slightly misleading error code, or should I close this issue?

Sincerely,
James

**Comment by zlesnr** [comment] 2020-09-10 15:27
I'm not sure if something changed there, but I doubt if there was a backwards-incompatible change that was made without release notes of some kind.  I'd suggest trying that query out in the UI.  The `From K8sContainerSample Select` pattern is helpful to get the autocomplete results to show up, since the query suggestions need to know which table you are selecting from, and so putting the from first aids in that visual queue. 

As for the errors, we're aware that the errors are not getting surfaced correctly, and the teams that have the ability to impact that are also aware and we expect to be tracking that.  I'll close this out, but if something else comes up, do let us know.

**Closed by zlesnr** 2020-09-10 15:27 UTC
Labels: question
