### ISSUE TITLE
Terraform crash after newrelic provider upgrade to v2.4.1

### ISSUE THREAD

**Issue by skragavan** [newrelic/terraform-provider-newrelic#811] opened 2020-07-30 03:38 UTC
Hi there,

I was using 

provider "newrelic" {
  version = "~> 2.2"
}

Terraform crashed when executing "terraform plan" after a change in newrelic component.

Realized it downloaded latest newrelic “Downloading plugin for provider "newrelic" (terraform-providers/newrelic) 2.4.1..."

### Terraform Version
Terraform v0.12.28
+ provider.aws v2.70.0
+ provider.newrelic v2.4.1

### Affected Resource(s)
- newrelic

### Debug Output
I got the following error when executing "terraform plan" after a change in newrelic component

Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled

panic: runtime error: invalid memory address or nil pointer dereference

[DEBUG] plugin.terraform-provider-newrelic_v2.4.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee1517]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform1 so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Workaround

It worked after changing NewRelic provider to particular version

provider "newrelic" {
  version       = "2.2.1"
}

**Comment by sanderblue** [comment] 2020-07-30 15:54
@skragavan Hi there! Thanks for reporting. I can't reproduce this with my current configuration. Can you provide more of your configuration (sensitive data redacted)? We won't be able to tell which data source or resource is causing the issue without that information. Thanks.

**Comment by skragavan** [comment] 2020-07-31 00:53
Hi @sanderblue, Thanks for your response.

resource "newrelic_alert_policy" "alerts" {
  name = "Alerts"
}

I already have my alerts created using version 2.2.1. So now I tried to update with just above config with updated newrelic version and I am getting the following error
Error: rpc error: code = Canceled desc = context canceled


panic: runtime error: invalid memory address or nil pointer dereference
2020-07-31T00:51:07.068Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee1517]
2020-07-31T00:51:07.069Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: 
2020-07-31T00:51:07.069Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: goroutine 45 [running]:
2020-07-31T00:51:07.070Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.flattenAlertThreshold(0xc00000df00, 0x11a3006, 0x15, 0xfa6200)
2020-07-31T00:51:07.071Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_infra_alert_condition.go:129 +0xa7
2020-07-31T00:51:07.071Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.flattenInfraAlertCondition(0xc0002f2540, 0xc000379c70, 0xc0002f2540, 0x0)
2020-07-31T00:51:07.072Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/structures_newrelic_infra_alert_condition.go:113 +0x491
2020-07-31T00:51:07.072Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: github.com/newrelic/terraform-provider-newrelic/v2/newrelic.resourceNewRelicInfraAlertConditionRead(0xc000379c70, 0x1004f20, 0xc000321260, 0xc000379c70, 0x0)
2020-07-31T00:51:07.072Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/work/terraform-provider-newrelic/terraform-provider-newrelic/newrelic/resource_newrelic_infra_alert_condition.go:231 +0x283
2020-07-31T00:51:07.072Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000455ef0, 0xc0002a1c20, 0x1004f20, 0xc000321260, 0xc00009dbd8, 0x0, 0x0)
2020-07-31T00:51:07.073Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:460 +0x119
2020-07-31T00:51:07.073Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00009cb50, 0x1471ca0, 0xc0004a06c0, 0xc0004a8300, 0xc00009cb50, 0xc0004a06c0, 0xc000531ba0)
2020-07-31T00:51:07.073Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x114e240, 0xc00009cb50, 0x1471ca0, 0xc0004a06c0, 0xc0004a82a0, 0x0, 0x1471ca0, 0xc0004a06c0, 0xc0004c8000, 0x175)
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a4000, 0x147e300, 0xc0004fe180, 0xc0000c4700, 0xc000137bf0, 0x1c747d0, 0x0, 0x0, 0x0)
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x50a
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: google.golang.org/grpc.(*Server).handleStream(0xc0000a4000, 0x147e300, 0xc0004fe180, 0xc0000c4700, 0x0)
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccd
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000098360, 0xc0000a4000, 0x147e300, 0xc0004fe180, 0xc0000c4700)
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-07-31T00:51:07.074Z [DEBUG] plugin.terraform-provider-newrelic_v2.4.1:     /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1
2020-07-31T00:51:07.080Z [DEBUG] plugin: plugin process exited: path=/build/components/opralog-newrelic/.terraform/plugins/linux_amd64/terraform-provider-newrelic_v2.4.1 pid=71 error="exit status 2"
2020/07/31 00:51:07 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Canceled desc = context canceled
2020/07/31 00:51:07 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2020/07/31 00:51:07 [TRACE] [walkRefresh] Exiting eval tree: newrelic_infra_alert_condition.offline
2020/07/31 00:51:07 [TRACE] vertex "newrelic_infra_alert_condition.offline": visit complete
2020/07/31 00:51:07 [TRACE] dag/walk: upstream of "provider.newrelic (close)" errored, so skipping
2020/07/31 00:51:07 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-07-31T00:51:07.081Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-07-31T00:51:07.353Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by calillo** [comment] 2020-08-06 13:27
Hi,

I have the same issue. I created my alerts with version 2.2.x and with all the major ones of 2.4.0 included it crashes, it only works with 2.3.0
Unfortunately I would like to use the new features in 2.5.0 but I can't, I'm stuck in version 2.3.0

Please fix this issue,
Thanks in advance

**Comment by ctrombley** [comment] 2020-08-06 16:13
Hi @calillo, can you share your configuration with sensitive pieces redacted?

**Comment by zlesnr** [comment] 2020-08-06 16:56
Looking at the stack trace above, the resource mentioned is the `newrelic_alert_policy`, but the stack trace is coming from `newrelic.flattenAlertThreshold`, which we only use in the `structures_newrelic_infra_alert_condition` file.

**Comment by zlesnr** [comment] 2020-08-06 16:57
I've put up https://github.com/newrelic/terraform-provider-newrelic/pull/832 to help, but I'd still like to see the configurations for the failing resources here pelase.

**Comment by zlesnr** [comment] 2020-08-13 20:40
This should be resolved in the next release.

**Closed by zlesnr** 2020-08-13 20:40 UTC
Labels: bug, waiting-response
