### ISSUE TITLE
Add Data Source for AWS Lambda Layers

### ISSUE THREAD

**Issue by ftieben** [newrelic/terraform-provider-newrelic#1717] opened 2022-03-21 07:46 UTC
### Feature Description
We are deploying our AWS Lambdas with Terraform and add the NewRelic Layer there as well. Currently the Layer Version need to be changed manually.
It would be realy nice to get a little data resource that will give you the full ARN of the layer for the given Runtime Region pair. 

You can get the Data from here:
https://layers.newrelic-external.com/

**Comment by kidk** [comment] 2022-03-21 08:17
Thanks for the request @ftieben 

This is a duplicate of #1032. I'll give a status update in that ticket.

**Closed by kidk** 2022-03-21 08:17 UTC
