### ISSUE TITLE
"account_id" is supposed to be Optional, but it is required, resulting in an error

### ISSUE THREAD

**Issue by yuzujoe** [newrelic/terraform-provider-newrelic#1971] opened 2022-08-31 09:38 UTC
Hi there,

Thank you for opening an issue. In order to better assist you with your issue, we kindly ask to follow the template format and instructions. Please note that we try to keep the Terraform issue tracker reserved for **bug reports** and **feature requests** only. General usage questions submitted as issues will be closed and redirected to New Relic's Explorers Hub https://discuss.newrelic.com/c/build-on-new-relic/developer-toolkit.

## Please include the following with your bug report

> :warning: **Important:** Failure to include the following, such as omitting the Terraform configuration in question, may delay resolving the issue.

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
`1.2.7`

### Affected Resource(s)
- `newrelic_notification_destination`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
resource "newrelic_notification_destination" "slack" {
  name       = "newrelic_notification_slack"
  type       = "WEBHOOK"

  property {
    key   = "url"
    value = "<slack url value>"
  }

  auth_basic {
    user     = ""
    password = ""
  }
}
```

### Actual Behavior
The argument "account_id" is required, but no definition was found.

### Expected Behavior
I expect it to run without problems at terraform plan runtime

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Debug Output
https://gist.github.com/yuzujoe/eab719c9f235b05e746438a58f2a3989

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
N/A

**Comment by NSSPKrishna** [comment] 2022-09-02 11:08
This is duplicate of #1960

**Closed by NSSPKrishna** 2022-09-02 11:08 UTC
Labels: bug
