### ISSUE TITLE
newrelic_synthetics_monitor is not providing guid

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/terraform-provider-newrelic#1055] opened 2020-12-09 09:33 UTC
**newrelic_synthetics_monitor** doesn't have guid in outputs which prevents tagging it with **newrelic_entity_tags**.

https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_monitor

**Comment by ctrombley** [comment] 2020-12-09 17:18
Duplicate of #756.  There is a workaround in that issue that may work for you @echoAlexey.  Give it a try and let us know.  I am going to close this issue in favor of tracking progress in #756.

**Closed by ctrombley** 2020-12-09 17:18 UTC
