### ISSUE TITLE
newrelic_notification_destination continually tries to apply changes

### ISSUE THREAD

**Issue by jsbnr** [newrelic/terraform-provider-newrelic#2111] opened 2022-11-18 12:07 UTC
The newrelic_notification_destination resource keeps trying to apply changes on every apply.

It always tries to remove `auth_basic` and updated the properties, including setting a source attribute.

### Terraform Version
Terraform: v1.3.4
Provider: v3.7.1

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_notification_destination`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
resource "newrelic_notification_destination" "example" {
  account_id = var.accountId
  name = "some name"
  type = "EMAIL"

  property {
    key = "email"
    value = "example@example.com"
  }
}
```

### Actual Behavior

Every apply it gives the same change set:

```
  ~ resource "newrelic_notification_destination" "demo" {
        id         = "xxx-xxx-xx"
        name       = "some name"
        # (4 unchanged attributes hidden)

      - auth_basic {}

      - property {
          - key   = "email" -> null
          - value = "example@example.com" -> null
        }
      - property {
          - key   = "source" -> null
          - label = "terraform-source-internal" -> null
          - value = "terraform" -> null
        }
      + property {
          + key   = "email"
          + value = "example@example.com"
        }
      + property {
          + key   = "source"
          + label = "terraform-source-internal"
          + value = "terraform"
        }
    }
```

### Expected Behavior
There should be no changes.

### Steps to Reproduce
Create an email destination and then re-apply.

**Comment by IliaShurygin** [comment] 2022-11-18 17:58
Duplicate of https://github.com/newrelic/terraform-provider-newrelic/issues/2008

**Closed by IliaShurygin** 2022-11-18 17:58 UTC
