### ISSUE TITLE
Allow to manage Synthetic monitor downtimes via terraform

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/terraform-provider-newrelic#1022] opened 2020-11-12 15:10 UTC
Allow to manage Synthetic monitor downtimes via terraform

At the moment we are managing synthetic monitors via terraform.
Creating monitor downtimes is not possible and requires manual work.

**Comment by zlesnr** [comment] 2020-11-12 18:06
I think this may be supported by the muting rules API soon.

**Comment by jthurman42** [comment] 2021-03-02 21:12
Duplicate of #980

**Closed by jthurman42** 2021-03-02 21:12 UTC
Labels: enhancement
