### ISSUE TITLE
terraformApply FAILED with Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by nvuppala** [newrelic/terraform-provider-newrelic#1531] opened 2021-11-17 20:38 UTC
### Terraform Version
Terraform v0.13.6

### Affected Resource(s)
Terraform plan:

```
resource "newrelic_nrql_alert_condition" "alert name" {
        account_id                     = [account id]
        aggregation_window             = 60
        baseline_direction             = "UPPER_ONLY"
        close_violations_on_expiration = false
        description                    = "desc"
        enabled                        = true
        expiration_duration            = 0
        fill_value                     = 0
        id                             = [id]
        name                           = [name]
        open_violation_on_expiration   = false
        policy_id                      = [policyid]
        runbook_url                    = ""
        type                           = "baseline"
        violation_time_limit_seconds   = 86400

      ~ critical {
            duration              = 0
            operator              = "above"
          ~ threshold             = 1 -> 5
            threshold_duration    = 300
            threshold_occurrences = "all"
        }

        nrql {
            evaluation_offset = 3
            query             = [query]
        }
    }
```

### Terraform Configuration
newrelic   version="2.32.0"

### Actual Behavior
```
When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" changed the planned action from
Update to Create.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.violation_time_limit: was null, but now cty.UnknownVal(cty.String).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.account_id: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.aggregation_window: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.fill_value: was cty.NumberIntVal(0), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.open_violation_on_expiration: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.expiration_duration: was cty.NumberIntVal(0), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.id: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.close_violations_on_expiration: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.critical[0].time_function: was cty.StringVal(""), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.critical[0].duration: was cty.NumberIntVal(0), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan

When expanding the plan for
[alert name]
to include new values learned so far during apply, provider
"registry.terraform.io/newrelic/newrelic" produced an invalid new value for
.nrql[0].since_value: was cty.StringVal(""), but now null.
```

### Expected Behavior
What should have happened?
We are attempting to update the alert and update should succeed.

### Steps to Reproduce

`terraform apply`

**Comment by kidk** [comment] 2021-11-18 11:13
@nvuppala does this also happen with the latest version of the New Relic provider? Your version is a couple of versions behind.

**Comment by nvuppala** [comment] 2021-11-18 18:59
@kidk I have not tested with the latest version, I can try. But, do you know what is the issue and if the latest version will resolve the issue?

**Comment by nvuppala** [comment] 2021-11-18 22:06
@kidk  I upgraded the provider version to 2.32.0 and I still got the same errors.

**Comment by nvuppala** [comment] 2021-11-23 18:52
Can someone look into this issue? It is causing a lot of inconvenience

**Comment by ericSpence** [comment] 2021-12-01 14:08
We are seeing a slight variation on this bug as well 
`╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to newrelic_alert_channel.alert_channel_0, provider
│ "provider[\"registry.terraform.io/newrelic/newrelic\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵`

**Comment by emetcalf9** [comment] 2021-12-28 20:09
I have not been able to reproduce this error using version 2.32.0 of the provider. Based on the original message, it looks like you were just trying to change the threshold value on the condition. Can you provide the rest of the configuration info for that condition as well so I can test this out with the same data?

**Comment by emetcalf9** [comment] 2022-01-14 00:32
I am going to close this issue now because we are unable to reproduce the error. If this is still happening, please create a new issue with any extra details that we can use to reproduce this and we will look into it again.

**Closed by emetcalf9** 2022-01-14 00:32 UTC
Labels: group-alerts
