### ISSUE TITLE
newrelic_entity is not fetching entities by provided account ID

### ISSUE THREAD

**Issue by alejandro-delgado-garcia** [newrelic/terraform-provider-newrelic#834] opened 2020-08-07 19:36 UTC
### Feature Description
When using the data source **newrelic_entity** I think we should also search the entity by account ID as the result of the query could return multiple entities if they have the same name across different sub-accounts.
Using an API key from one sub-account is returning entities from other sub-accounts.

### Describe Alternatives
To solve our issue we had to manually add a tag to our browser application and use that tag with the **newrelic_entity**.

**Comment by zlesnr** [comment] 2020-08-07 21:22
Hi, thank you for raising the issue.  Looking over the graphql API docs, it doesn't look like the entity search "queryBuilder" allows for searching by accountID, but we could potentially do this client side.  It looks like we have the account_id already present on the resource, so are you thinking a new attribute perhaps that scopes the results to those that match the account id on the resource?

**Comment by alejandro-delgado-garcia** [comment] 2020-08-07 22:02
Yes exactly, that sounds good !

Or maybe it should be the default behavior as the account id is already a required attribute of the provider so to me all the queries should filter the results by the account id. So maybe we don't even need to specify it in the resource configuration. https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/provider_configuration

**Comment by kidk** [comment] 2022-07-05 10:01
Duplicate of #1041. Will continue conversation there.

**Closed by kidk** 2022-07-05 10:01 UTC
Labels: enhancement, group-general
