### ISSUE TITLE
Dynamic blocks do not fix the order in which listings are processed

### ISSUE THREAD

**Issue by melumuccu** [newrelic/terraform-provider-newrelic#1720] opened 2022-03-22 04:34 UTC
### Terraform Version
```
# tf -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/newrelic/newrelic v2.39.2

# tf providers

Providers required by configuration:
.
├── provider[registry.terraform.io/newrelic/newrelic] 2.39.2
├── module.base
│   └── provider[registry.terraform.io/newrelic/newrelic]
├── module.future
│   └── provider[registry.terraform.io/newrelic/newrelic]
├── module.nrql
│   └── provider[registry.terraform.io/newrelic/newrelic]
├── module.past
│   └── provider[registry.terraform.io/newrelic/newrelic]
├── module.synthetics_monitor
│   └── provider[registry.terraform.io/newrelic/newrelic]
├── module.time_unit
│   └── provider[registry.terraform.io/newrelic/newrelic]
└── module.urls
    └── provider[registry.terraform.io/newrelic/newrelic]

Providers required by state:

    provider[registry.terraform.io/newrelic/newrelic]
```

### Affected Resource(s)
- `newrelic_one_dashboard`

### Terraform Configuration
- main.tf
```hcl
terraform {
  required_version = "~> 1.0"
  required_providers {
    newrelic = {
      version = "2.39.2"
      source = "newrelic/newrelic"
    }
  }
}

provider "newrelic" {}
```

- test.tf
```hcl
//-------------------------------------
// resource
//-------------------------------------
resource "newrelic_one_dashboard" "test_lighthouse" {
  name = "(test)Lighthouse_goonet-prod"
  page {
    name = "lighthouse"
    dynamic "widget_line" {
      for_each = local.test_targets
      iterator = target
      content {
        title  = module.urls.urls["${target.value}"].url_name
        row    = target.key + 1
        column = 1     
        nrql_query {
          query = <<EOF
${module.nrql.nrql["lighthouse_dashboard"].nrql1}  average(custom.performanceScore) AS 'desktop'
${module.nrql.nrql["lighthouse_dashboard"].nrql2}  monitorName = '(test)LIGHTHOUSE - ${target.key} - desktop'
${module.nrql.nrql["lighthouse_dashboard"].nrql3}
          EOF
        }
      }
    }
  }
}
//-------------------------------------
// locals
//-------------------------------------
locals {
  test_targets = [
    "https://www.goo-net.com/",
    "https://www.goo-net.com/catalog/TOYOTA/",
    "https://www.goo-net.com/catalog/TOYOTA/ALPHARD/",
    "https://www.goo-net.com/magazine/",
  ]
}
```

### Actual Behavior
After "apply", "change" was detected when "plan" was performed without modifying any source code.

### Expected Behavior
No "change" was detected 

### Steps to Reproduce
1. $ terraform apply
2. $ terraform plan

logs
https://gist.github.com/melumuccu/2d9254ff3cf3d0135fef2b30cc6c4ac0

**Comment by melumuccu** [comment] 2022-03-23 01:47
Thanks for the reply.

> While reviewing the script we are suspecting that some changes were made outside of the terraform,
for example :
> a. Column value changes from 1 to 5.
> b. Condition changes in NRQL query.

Upon additional investigation, it appears that the order in which the arrays are processed in "for_each" in the dynamic block is undefined.

Please see documents that follow.
The dashboard does not seem to change before or after "apply".

> 1. Import the dashboard to JSON format. 
before "apply": https://gist.github.com/melumuccu/8f2e59b415753f5bb46e575827fb6ce7
after "apply": https://gist.github.com/melumuccu/8f786d02bc95b4efe6f06561df51095f

I tried to get a before and after, but there is no difference...

> 2. Also provide the dashboard screenshots (if possible before and after changes) to the email
I sent you an email. The title is this issue one.

**Comment by shiva-bandari** [comment] 2022-03-24 14:37
Hi @melumuccu
This is a duplicate of the issue: https://github.com/newrelic/terraform-provider-newrelic/issues/1452.
There is nothing we can do now, however we'll keep this in mind when redesigning the dashboard resource.

**Closed by shiva-bandari** 2022-03-24 14:37 UTC

**Comment by melumuccu** [comment] 2022-03-25 00:57
@shiva-bandari 
OK, Thanks.
For now, I will use "ignore_changes" in "lifecycle".
I'll try to deal with it by commenting out "ignore_changes" when do "apply".
