### ISSUE TITLE
API misbehavior

### ISSUE THREAD

**Issue by RizwaanShaik** [newrelic/terraform-provider-newrelic#1739] opened 2022-04-04 09:58 UTC
### Terraform Version

`Terraform version 1.1.6` 
`provider version 2.37.0` 

### Affected Resource(s)
- `newrelic_one_channel_bindings`

### Actual Behavior
`We are seeing an issue regarding newrelic api. We are currently on terraform new relic provider version 2.37.0. Here is what we see:
Error: GET https://api.newrelic.com/v2/alerts_channels.json?page=4 giving up after 4 attempt(s): Get “https://api.newrelic.com/v2/alerts_channels.json”
So, basically this happens only with this particular API call only when the provider reaches to invoke Page 4 is when it errors out and not before that. That means the API calls to api.newrelic.com are working.
To test out the theory, we commented out the part where we do policy to channel binding and just ran everything else. It did not error out.`

### Expected Behavior
What should have happened?
`Easy workflow of terraform plan and apply.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan and apply`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://gist.github.com/RizwaanShaik/2a2b05da07a0d2b1b7587fe01addf9fe

### Other links

Post on discuss.newrelic: https://discuss.newrelic.com/t/help-lookup-api-newrelic-com-server-misbehaving/179740/5?u=rizwaan.shaik
Newrelic support case: https://support.newrelic.com/s/case/5008W00000m03zeQAA/api-misbehavior

**Comment by SiddhantAgarwal17** [comment] 2022-04-04 10:31
Just to note here, that this is blocking our production deliverables. This started occurring in later half of March, 2022

**Comment by kidk** [comment] 2022-04-04 14:19
Hi @SiddhantAgarwal17 

We've escalated this with the alert API team. We will get back to you when we have a reply.

**Comment by baNROne** [comment] 2022-04-04 22:24
Hi @SiddhantAgarwal17 👋 Looking into this now...

Please post your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.

Additionally, can you please try using the latest version of the provider and let us know what you see?

**Comment by RizwaanShaik** [comment] 2022-04-05 06:47
> Hi @SiddhantAgarwal17 👋 Looking into this now...
> 
> Please post your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
> 
> Additionally, can you please try using the latest version of the provider and let us know what you see?

Provider Configuration

provider "newrelic" {
  api_key    = *****
  account_id = *****
}

/*
  Restrict the Terraform Version.
*/
terraform {
  required_version = "~> 1.1.6"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "2.37.0"
    }
  }
}

**Comment by RizwaanShaik** [comment] 2022-04-05 06:50
> Hi @SiddhantAgarwal17 👋 Looking into this now...
> 
> Please post your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
> 
> Additionally, can you please try using the latest version of the provider and let us know what you see?

Resource Configuration

resource "newrelic_alert_policy_channel" "alert_policy_channel_binding" {
  count       = length(local.policies) > 0 ? length(local.policies) : 0
  policy_id   = newrelic_alert_policy.alert_policies[local.policies[count.index]].id
  channel_ids = sort(jsondecode(local.alert_user_channels[split("_", newrelic_alert_policy.alert_policies[local.policies[count.index]].name)[0]]))
}

**Comment by RizwaanShaik** [comment] 2022-04-05 11:09
@baNROne We tried using the newrelic provider version 2.41.1 but ran into the same issue

**Comment by baNROne** [comment] 2022-04-05 22:25
Thanks for sharing that info @SiddhantAgarwal17

Can you please also share the configuration of the `alert_user_channels` locals block?

I'm not seeing any recent changes to how we retrieve channel details and I've been able to paginate up to, and past, page 4 with the `https://api.newrelic.com/v2/alerts_channels.json` endpoint. I'm wondering if there's anything about the locals block that could be causing an issue.

**Comment by SiddhantAgarwal17** [comment] 2022-04-06 04:49
> alert_user_channels

```

data "external" "user_channels" {
  program = ["ruby", var.user_channel_script_path]
  query = {
    api_key               = var.api_key
    account_id            = var.account_id
    recipients_by_service = jsonencode(var.recipients_by_service)
  }
}

locals {
  // Stores the result of user channels external data source into a local variable.
  alert_user_channels = data.external.user_channels.result
}
```

**Comment by SiddhantAgarwal17** [comment] 2022-04-06 04:54
The external script does something like this: 
```ruby
# Method to get list of user channels.
def get_user_channels
  notification_channel_obj = NotificationChannelsNerdGraphAPI.new
  notification_channels = notification_channel_obj.get_notification_channels(DATA['account_id'])
  user_channels = parse_data(notification_channels)
  user_channels_by_service_unfiltered = {}
  JSON.parse(RECIPIENTS_BY_SERVICE).each do |service, contacts|
    contacts_list = contacts.split(',')
    contact_id_list = []
    contacts_list.each do |contact|
      if (contact_key = user_channels.keys.find { |k| k.downcase.include? contact.downcase })
        contact_id_list.append(user_channels[contact_key].to_i)
      end
    end
    user_channels_by_service_unfiltered.store(service, contact_id_list.to_s) unless contact_id_list.empty?
  end
  user_channels_by_service_unfiltered.to_json
end
```
where 
NerdGrapAPI looks something like:

```ruby
NotificationChannelsNerdGraphAPI::CLIENT.parse <<-'GRAPHQL'
  query($accountid: Int!,$nextCursor: String!){
    actor {
      account(id: $accountid) {
      alerts {
        notificationChannels(cursor: $nextCursor) {
          channels {
            id
            name
            type
            }
          nextCursor
          }
        }
      }
    }
  }
```

**Comment by SiddhantAgarwal17** [comment] 2022-04-06 04:59
and the above API is invoked something like this: 

```ruby
  # Method to get all channels from graphQL
  # accountid : New relic account id.
  # next_cursor : Pagination cursor for graphQL
  def get_graphql_results(accountid, notification_channels, next_cursor = nil)
    intial_result = if next_cursor
                      NotificationChannelsNerdGraphAPI::CLIENT.query(ChannelsPaginationQuery, variables: { accountid: accountid.to_i, nextCursor: next_cursor }, context: { api_key: API_KEY })
                    else
                      NotificationChannelsNerdGraphAPI::CLIENT.query(NotificationChannelQuery, variables: { accountid: accountid.to_i }, context: { api_key: API_KEY })
                    end
    raise "Error Returned by New Relic: #{intial_result.to_h['errors']}  " if intial_result.to_h['errors']&.length&.positive?

    next_cursor = intial_result.data.actor.account.alerts.notification_channels.to_h['nextCursor']
    result = intial_result.data.actor.account.alerts.notification_channels.to_h['channels']
    notification_channels << result

    next_cursor
  end
```

**Comment by SiddhantAgarwal17** [comment] 2022-04-07 04:54
@baNROne Any luck with this one yet?

**Comment by baNROne** [comment] 2022-04-07 23:25
I'm still a bit confused @SiddhantAgarwal17 . The code you've shared is using the NerdGraph API to pull down the list of notification channels. However, the provider has this ability built-in (via [newrelic-client-go](https://github.com/newrelic/newrelic-client-go/blob/0b2cf7ffb16cc2eba775d937a0fc6be3d73450cd/pkg/alerts/channels.go#L85)), which it does using the REST API.

I'd like to try to understand what need is not being met by the provider? Are you trying to access channels cross-account? (This ability was recently added [here](https://github.com/newrelic/terraform-provider-newrelic/pull/1676)) 

I can't offer support for errors arising from the use of the custom Ruby code, but if you can show me how the provider returns this error without custom code I'd be happy to continue digging into it.

**Comment by SiddhantAgarwal17** [comment] 2022-04-08 10:05
> I'm still a bit confused @SiddhantAgarwal17 . The code you've shared is using the NerdGraph API to pull down the list of notification channels. However, the provider has this ability built-in (via [newrelic-client-go](https://github.com/newrelic/newrelic-client-go/blob/0b2cf7ffb16cc2eba775d937a0fc6be3d73450cd/pkg/alerts/channels.go#L85)), which it does using the REST API.
> 
> I'd like to try to understand what need is not being met by the provider? Are you trying to access channels cross-account? (This ability was recently added [here](https://github.com/newrelic/terraform-provider-newrelic/pull/1676))
> 
> I can't offer support for errors arising from the use of the custom Ruby code, but if you can show me how the provider returns this error without custom code I'd be happy to continue digging into it.

We are not trying to access channels across account. This was added back when this ability was not part of the provider code. We haven't just replaced it yet because it has been working since last couple of years as is. The 500 internal server error is returned by the New Relic API. Doesn't seem to be an issue with the external code as of today. I did raise a direct request earlier for support and I was re-directed here by the support team

**Comment by SiddhantAgarwal17** [comment] 2022-04-08 10:05
Is it possible to see what caused the Internal Server Error on the New Relic API side corresponding to this request ID: `d061a0b2e50c3972271816bbf7abb3be`

**Comment by baNROne** [comment] 2022-04-12 17:47
Hi @SiddhantAgarwal17. I appreciate your patience while we've been digging into this. We've identified the issue retrieving channels. We've created a ticket to resolve this and will update you when we've pushed a fix.

**Comment by SiddhantAgarwal17** [comment] 2022-04-13 09:21
Thanks @baNROne! Let me know as soon as this is out and my team would be happy to run a quick test.

**Comment by mattandes** [comment] 2022-04-13 12:23
@baNROne Can you provide more information on this issue? Is this issue on the Terraform side or the New Relic API side? A client I work with is also experiencing this issue and we have not been having luck with our New Relic support case. Can you provide the link and/or case number to the ticket you've created so we can track that and/or provide it to our New Relic support people?

**Comment by SiddhantAgarwal17** [comment] 2022-04-13 12:56
@mattandes Our case was closed without any luck. We were re-directed here by the New Relic support team. Based on my observations so far, it seems to be occurring from the New Relic server. I was seeing this issue consistently about couple of weeks ago. But since, since last few days, it has changed to intermittent issue. I would suggest to track this Github issue. @baNROne has identified the issue and working on resolving the same as mentioned here: https://github.com/newrelic/terraform-provider-newrelic/issues/1739#issuecomment-1097015900

**Comment by baNROne** [comment] 2022-04-13 20:30
Hi @mattandes and @SiddhantAgarwal17

The issue does appear to lie outside of the provider. We've identified an expensive JOIN query that is timing out, causing errors to surface downstream in the REST API used by the provider. Since this affects the provider, I'm tracking the issue and will update this thread when it is resolved. For support case tracking, the support team can reference `AINTER-8500`.

**Comment by SiddhantAgarwal17** [comment] 2022-04-20 04:49
@baNROne  When can we expect this to be released?

**Comment by baNROne** [comment] 2022-04-20 18:15
Hi @SiddhantAgarwal17. We don't offer a release timeline for features or fixes on our open source projects. What I can say is that work is currently being done toward resolving this issue. There are a number of tickets linked to this issue, about half of which have been completed. As soon as all of the work has been completed we'll be sure to update this thread.

**Comment by RizwaanShaik** [comment] 2022-06-01 11:41
@baNROne Any update on this as we are blocked for a long time now?

**Comment by RizwaanShaik** [comment] 2022-07-12 05:14
Just checking in to see if there is an update.

**Comment by baNROne** [comment] 2022-07-15 22:50
@RizwaanShaik The ticket tracking the work was closed on June 30th. My apologies for not updating this thread sooner.

From our end, it appears that all of the work was completed successfully. Our monitoring shows a large volume of successful requests from what I believe is your account. When did you last run into the issue?

**Comment by kidk** [comment] 2022-08-15 09:01
I'm going to close this ticket as the issue is resolved. Please don't hesitate to reply if this is still and issue for you.

**Closed by kidk** 2022-08-15 09:01 UTC
Labels: group-alerts
