### ISSUE TITLE
 Automate the enablement of integration providers, e.g AWS

### ISSUE THREAD

**Issue by Constantin07** [newrelic/terraform-provider-newrelic#62] opened 2018-11-05 16:29 UTC
At the moment enabling integration provider, e.g. for AWS requires manual configuration under Infrastructure>Integrations. It does require the Amazon account id and role to assume for pulling out CloudWatch metrics.

It would nice to have a newrelic resource so that this can be automated given the fact that the below details are already known:

- AccountID
- Role to be assumed
- External ID

**Comment by jgminer** [comment] 2019-01-22 22:38
It appears you can sort of get around this by using the `newrelic_nrql_alert_condition` TF provider instead, about to test the same myself.

**Comment by AlbertoGoYu** [comment] 2019-02-18 14:10
There's that GraphQL API that can help with that: 
https://developer.newrelic.com/technology/graphql
Docs with examples here: 
https://docs.newrelic.com/docs/apis/graphql-api/tutorials/manage-your-aws-azure-google-cloud-integrations-graphql-api

Disclaimer: I work at New Relic

**Comment by Constantin07** [comment] 2019-12-17 12:00
Thanks @AlbertoGoYu though not quite clear to me how would I run a query not via NerdGraph GraphiQL explorer ? I cannot find an example of command line invocation, e.g. using `curl` ...

**Comment by ctrombley** [comment] 2019-12-17 17:55
@Constantin07 here are some curl-based examples: https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph

**Comment by jthurman42** [comment] 2019-12-17 19:39
The current backing library does not support the GraphQL endpoint that would enable this in Terraform.  We (New Relic) will be doing some of that enablement work in the next few weeks, and this seems like a great use-case for that work.  For reference, the current roadmap for the New Relic team curating this provider is available here: https://newrelic.github.io/developer-toolkit/roadmap/

**Comment by gkiranch** [comment] 2020-02-06 07:38
is there an ETA on the above request?

**Comment by jthurman42** [comment] 2020-03-02 23:46
The backend library (newrelic/newrelic-client-go) now supports queries to NerdGraph opening up the ability to manage cloud integrations.  However, that's a large chunk of work so this is likely to take a while to move forward.

**Comment by aboyanov** [comment] 2020-04-20 17:28
@jgminer did you managed to do it using the`newrelic_nrql_alert_condition` resource? If so can you please share it here, because currently, I'm trying to integrate my AWS account with my NewRelic one via Terraform, but without a success so far. 

P.S. If anyone has figured it out how to integrate an AWS profile programmatically (e.g. curl, terraform, python or whatever) it would be highly appreciated to share an example :) Thanks in advance! Cheers!

**Comment by jthurman42** [comment] 2020-04-20 18:36
@aboyanov There is a tutorial for using the API to connect New Relic to your cloud provider located here: https://docs.newrelic.com/docs/apis/graphql-api/tutorials/nerdgraph-graphiql-cloud-integrations-api-tutorial

Adding this work into the New Relic provider for Terraform is still a future item, though we'd be happy review / merge in a PR if the community wants to assist in moving this forward faster.

**Comment by jgminer** [comment] 2020-04-20 19:08
@aboyanov yes - ended up using NRQL instead and was able to pull any metrics from AWS, within reason. Easy to protoype in the Insights UI as well.

**Comment by aboyanov** [comment] 2020-04-27 13:46
@jthurman42 @jgminer Thanks for the help!
For others that come across and are looking for what I was looking for (i.e. programmatically link AWS account with NR and enable infra Services configuration like EC2, ECS, RDS, etc.) -> I used [this](https://github.com/newrelic/newrelic-lambda-cli/blob/master/newrelic_lambda_cli/api.py) Python implementation as a base that is using the "gql" Python's library to make NerdQL queries.

**Comment by Lonli-Lokli** [comment] 2022-02-19 17:31
So as of now there is still manual work required withing NewRelic in order to integrate AWS with NewRelic?

**Comment by aboyanov** [comment] 2022-02-19 17:49
@Lonli-Lokli not necessarily manual, but definitely outside of Terraform yeah. I used Python(code ref above in my previous comment) + null_resource to manage it with Terraform though. If you want I can send you the Terraform part as well. It's not a native TF resource, but it was working just fine in my case.

**Comment by kidk** [comment] 2022-02-21 08:43
We've been working on closing this gap. We'll soon be releasing it for connecting to AWS Metric stream and will include a full end to end example.

**Comment by Lonli-Lokli** [comment] 2022-02-21 09:43
@kidk The only part I left for now is Amazon CloudWatch Metric Streams integration, so will wait for your solution for now. Can you share estimated time for this code to be publicly available?

**Comment by kidk** [comment] 2022-02-21 11:19
It should be available next week.

**Comment by aroommen** [comment] 2022-03-08 00:28
@kidk Could you update us if it's available now?

**Comment by kidk** [comment] 2022-03-16 13:48
@aroommen It's available for metric stream: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/cloud_aws_link_account

We're still finishing up some work for the integrations, and will provide a full example soon.

**Comment by Lonli-Lokli** [comment] 2022-04-02 15:20
Hi all, I know it might be not the best time to ask, but maybe there is some eta for final sample? Appreciate some blogpost about that as well

**Comment by kidk** [comment] 2022-04-06 11:16
@Lonli-Lokli There's an example for Metric Stream in this PR: https://github.com/newrelic/terraform-provider-newrelic/pull/1730/files You would need to remove some of the code for integrations for now.

**Comment by Lonli-Lokli** [comment] 2022-04-08 11:14
@kidk I've tried to use your sample but it fails with this, do you know the reason?
```
│ Error: Access restricted
│
│   with newrelic_cloud_aws_link_account.newrelic_cloud_integration_push,
│   on main.tf line 78, in resource "newrelic_cloud_aws_link_account" "newrelic_cloud_integration_push":
│   78: resource "newrelic_cloud_aws_link_account" "newrelic_cloud_integration_push" {
│
╵
╷
│ Error: json: cannot unmarshal object into Go struct field .data.apiAccessCreateKeys.errors of type apiaccess.APIAccessKeyErrorInterface
│
│   with newrelic_api_access_key.newrelic_aws_access_key,
│   on main.tf line 86, in resource "newrelic_api_access_key" "newrelic_aws_access_key":
│   86: resource "newrelic_api_access_key" "newrelic_aws_access_key" {
│
╵
╷
│ Error: Access restricted
│
│   with newrelic_cloud_aws_link_account.newrelic_cloud_integration_pull,
│   on main.tf line 204, in resource "newrelic_cloud_aws_link_account" "newrelic_cloud_integration_pull":
│  204: resource "newrelic_cloud_aws_link_account" "newrelic_cloud_integration_pull" {
```

**Comment by Lonli-Lokli** [comment] 2022-04-08 14:12
What I noticed with terraform destoy - linked account still stays in NewRelic, manual removing leads later to error on terraform refresh/apply
Error: maximum retries reached: Linked account 'XXXX' for account 'YYYYYY' not found.

**Comment by Lonli-Lokli** [comment] 2022-04-08 14:48
Another error during creation, on retry it just fail  Error: ERR_INVALID_DATA Validation failed: "XXXXXXXXXX" AWS account that is associated to this role is already linked in this New Relic account
`
│ Error: ERR_INVALID_DATA : Validation failed: The ARN you entered does not permit the correct access to your AWS account - please check the ARN and try again.`

**Comment by kidk** [comment] 2022-04-10 14:21
Could you create tickets for these @Lonli-Lokli? The debug output is going to help us figure out what's going wrong. At the moment this is hard to reproduce.

**Comment by Lonli-Lokli** [comment] 2022-04-10 14:57
@kidk so you do not observe the same on empty AWS & NewRelic setup?

**Comment by Lonli-Lokli** [comment] 2022-04-12 15:45
I would like to admit that even I did nothing, my logs appearing in NR. I do not know why but mb this errors were just to slow creation of IAM roles in AWS.

**Comment by kidk** [comment] 2022-04-20 09:11
@Lonli-Lokli: I think that might be the case. There are delays on the AWS and New Relic side. Let us know if you have a fix so we can improve our example. 

I'm going to close this ticket as we've now released resources for all cloud providers 🥳 

We're going to add some more examples on this https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/cloud_integrations_guide but everyone should be able to use GCP and Azure right now.

If you encounter any issues or feature requests, don't hesitate to create a new ticket.

**Closed by kidk** 2022-04-20 09:11 UTC
Labels: enhancement, upstream, impact:med, group-general
