### ISSUE TITLE
Doing `terraform apply` with many `newrelic_synthetics_monitor` and `newrelic_synthetics_script_monitor` resources results in an error regarding a private location

### ISSUE THREAD

**Issue by arhill05** [newrelic/terraform-provider-newrelic#2083] opened 2022-11-01 18:44 UTC
Hi there,

# Please include the following with your bug report

- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_script_monitor`
- `newrelic_synthetics_monitor`
- data `newrelic_synthetics_private_location`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration
```hcl
data "newrelic_synthetics_private_location" "REDACTED" {
  name = "REDACTED"
}

resource "newrelic_synthetics_monitor" "simple_monitor" {
  for_each = {
    for app in local.ui_apps : app.monitor_name => app
  }
  period                                  = "EVERY_10_MINUTES"
  status                                  = "ENABLED"
  type                                    = "BROWSER"
  enable_screenshot_on_failure_and_script = true
  bypass_head_request                     = true
  verify_ssl                              = true

  name = "TF_NRV3_${each.value.monitor_name}"
  uri  = each.value.host_name

  tag {
    key    = "environment"
    values = ["${var.environment}"]
  }

  tag {
    key    = "server-group"
    values = [coalesce(each.value.server_group, "UNKNOWN")]
  }

  tag {
    key    = "managed-by-terraform"
    values = [true]
  }

  locations_private = [
    data.newrelic_synthetics_private_location.REDACTED.id
  ]
}

resource "newrelic_synthetics_script_monitor" "canary_synthetic_monitor" {
  account_id = var.account_id
  for_each = {
    for app in local.api_apps : app.monitor_name => app
  }

  location_private {
    guid = data.newrelic_synthetics_private_location.REDACTED.id
  }

  name   = "TF_NRV3_${each.value.monitor_name}"
  period = "EVERY_10_MINUTES"
  status = coalesce(each.value.is_enabled, true) ? "ENABLED" : "DISABLED"
  type   = "SCRIPT_API"

  tag {
    key    = "environment"
    values = ["${var.environment}"]
  }

  tag {
    key    = "server-group"
    values = [coalesce(each.value.server_group, "UNKNOWN")]
  }

  tag {
    key    = "managed-by-terraform"
    values = [true]
  }

  script = templatefile(
    "${path.module}/synthetics-scripts/${coalesce(each.value.custom_canary_script_name, "default.jstpl")}",
    {
      app = each.value
  })

  # These are commented out because this is the workaround
  # for using the "Node 10 (Legacy)" runtime in synthetics scripts.
  # The NewRelic provider won't let you set any version from the legacy
  # runtime versions, so if we ever upgrade to a new version we will need these properties.
  #
  # script_language = "JAVASCRIPT"
  # runtime_type         = "NODE_API"
  # runtime_type_version = "16.10"
}
```

### Actual Behavior
An error occurred several times, but not for all resources that were being created.

The error for each resource that fails to create is as follows:
```
Error: BAD_REQUEST Invalid location(s) specified: REDACTED
  with module.canary_synthetic_monitors.newrelic_synthetics_monitor.simple_monitor["REDACTED"], 
  on ..\..\src\synthetics_monitor.tf line 1, in resource "newrelic_synthetics_monitor" "simple_monitor": 
   1: resource "newrelic_synthetics_monitor" "simple_monitor" { 

Error: INTERNAL_SERVER_ERROR An error occurred during private location validation. Please try again. 
  with module.canary_synthetic_monitors.newrelic_synthetics_monitor.simple_monitor["REDACTED"], 
  on ..\..\src\synthetics_monitor.tf line 1, in resource "newrelic_synthetics_monitor" "simple_monitor": 
   1: resource "newrelic_synthetics_monitor" "simple_monitor" { 
```

### Expected Behavior
The apply should succeed without error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have at least 100 `newrelic_synthetics_script_monitor` or `newrelic_synthetics_monitor` resources to be created with a private location specified
2. `terraform apply`

### Important Factoids
Doing an apply again after seems to work fine with no changes to the configuration or private location. However, sometimes the monitor is created even when an error occurs and subsequent applies fail because Terraform is attempting to create a monitor that already exists.

**Comment by usfdmiller** [comment] 2022-11-04 18:57
The New Relic Terraform provider, from my experience, has suffered from persistent issues when trying to create synthetic monitors at scale.  It is incredibly frustrating.  Here is an example of a synthetic monitor I'm working on today.

```
locals {
  vlans = csvdecode(file("${path.module}/vlan.csv"))
}

resource "newrelic_synthetics_script_monitor" "sre_vlan_monitor" {
  for_each = { for vlan in local.vlans: vlan.monitor_name => vlan }

  name = each.value.monitor_name
  type = "SCRIPT_API"

  location_private {
    guid = data.newrelic_synthetics_private_location.dr_private_location.id
  }

  period = var.vlan_frequency
  status = var.vlan_enabled ? "ENABLED" : "DISABLED"

  script = templatefile("${path.module}/vlan.tpl", {
    target_name = each.value.target_name,
    target_uri  = each.value.target_ip
  })

  tag {
    key    = "DR"
    values = ["STAGE_VLAN"]
  }

  tag {
    key    = "SERVICE"
    values = ["VLAN"]
  }
}
```

For reference, this is version 1.3.4 of Terraform, and version 3.6.1 of the provider.

There are 59 entries in the CSV file, and maybe a quarter of the time "terraform apply" completes without error.  Here is the exception plaguing me today when trying to test.  

```
│ Error: TAGGING_ERROR: An unknown error occurred while adding tag(s) to monitor
│ 
│   with newrelic_synthetics_script_monitor.sre_vlan_monitor["DR-SRE-VLAN-6"],
│   on vlan.tf line 5, in resource "newrelic_synthetics_script_monitor" "sre_vlan_monitor":
│    5: resource "newrelic_synthetics_script_monitor" "sre_vlan_monitor" {
```

This one is a gem, because the monitor is created (with the tags it appears) but not added to the state.  Subsequent applies will fail because the monitor name already exists.  The monitor must be manually deleted before running Terraform again.  I can't expect automation pipelines to be used if they fail most of the time with errors that must be manually corrected.

I can also duplicate at least one of your errors with the given configuration.

```
resource "newrelic_synthetics_script_monitor" "script_api_monitor" {
  count = 100

  name = "New Relic Test ${count.index + 1}"
  type = "SCRIPT_API"

  location_private {
    guid = data.newrelic_synthetics_private_location.dr_private_location.id
  }

  period = "EVERY_15_MINUTES"
  status = "ENABLED"

#   script_language      = "JAVASCRIPT"
#   runtime_type         = "NODE_API"
#   runtime_type_version = "16.10"

  script = "$http.get('https://one.newrelic.com')"
}
```

I will frequently see the following error when applying that configuration.

```
│ Error: INTERNAL_SERVER_ERROR: An error occurred during private location validation. Please try again.
│ 
│   with newrelic_synthetics_script_monitor.script_api_monitor[46],
│   on simple.tf line 1, in resource "newrelic_synthetics_script_monitor" "script_api_monitor":
│    1: resource "newrelic_synthetics_script_monitor" "script_api_monitor" {
│ 
```

Occasionally when deleting monitors I will see this error.

```
╷
│ Error: Monitor does not exist or has already been deleted
│ 
│ 
╵
```

Although at least with this error it appears the monitor is actually deleted.  These issues aren't limited to the legacy runtime on a private location either, though admittedly the errors are fewer when creating monitors on public locations with a current runtime.  

```
resource "newrelic_synthetics_script_monitor" "script_api_monitor" {
  count = 100

  name = "New Relic Test ${count.index + 1}"
  type = "SCRIPT_API"

  locations_public = ["US_WEST_1"]

  period = "EVERY_15_MINUTES"
  status = "ENABLED"

  script_language      = "JAVASCRIPT"
  runtime_type         = "NODE_API"
  runtime_type_version = "16.10"

  script = "$http.get('https://one.newrelic.com')"

  tag {
    key    = "TARGET"
    values = ["NEWRELIC"]
  }

  tag {
    key    = "REASON"
    values = ["VERIFY"]
  }
}
```

I ran into this error with the above configuration.

```
│ Error: BAD_REQUEST: Monitor name already exists.
│ 
│   with newrelic_synthetics_script_monitor.script_api_monitor[14],
│   on simple.tf line 1, in resource "newrelic_synthetics_script_monitor" "script_api_monitor":
│    1: resource "newrelic_synthetics_script_monitor" "script_api_monitor" {
│ 
```

And it doesn't happen _as frequently_, but I'm still able to recreate the tag error.

```
│ Error: TAGGING_ERROR: An unknown error occurred while adding tag(s) to monitor
│ 
│   with newrelic_synthetics_script_monitor.script_api_monitor[14],
│   on simple.tf line 1, in resource "newrelic_synthetics_script_monitor" "script_api_monitor":
│    1: resource "newrelic_synthetics_script_monitor" "script_api_monitor" {
│ 
```

**Comment by mbazhlekova** [comment] 2022-11-11 21:40
We're working with the team that owns the Synthetics API to see what can be done about these errors. I'll create a ticket for us to look at what we can do from the Terraform side to better handle errors that occur during creation.

**Comment by getnilay** [comment] 2023-01-09 05:08
@mbazhlekova - any updates here, I can confirm we still see failures with provider `v3.8.0`. The first attempt where 2 Synthetics existed it failed with a similar error and it created one. On second attempt when all 3 Synthetics exists it failed as earlier. Ideally I would assume if it's considering name as identify to not create and pass the build.


```
Group 1
- Module /tf-resources/newrelic/resources/nonprod/synthetics/ping-monitor/REDACTED
- Module /tf-resources/newrelic/resources/nonprod/synthetics/scripted-api-monitor/REDACTED
- Module /tf-resources/newrelic/resources/nonprod/synthetics/scripted-api-monitor/REDACTED

Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) 
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

synthetic_monitor_id = "MjMwODQzM3xTWU5USHxNT05JCKN9SfDY4Yjk5MmZlLWJmMjQtNGYwOC05MmY5LTUzZDE4N2MzYTRiYQ"
newrelic_synthetics_script_monitor.script_monitor: Creating...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:
synthetic_monitor_id = "MjMwODQzM3xTWU5USHxNT05JVE9SfDhiNXCKNHJiLTZlNTQtNDc1My04ZTNiLTYzZjY1ZGYyZjM2NQ"

Error: BAD_REQUEST: Monitor name already exists.
```

**Comment by huzie** [comment] 2023-01-30 03:04
Any updates?

**Comment by karlforster** [comment] 2023-02-03 15:39
Getting the same issues here too, very frustrating. 
Even a workaround would be helpful.

**Comment by getnilay** [comment] 2023-02-07 23:17
@mbazhlekova  - is there a priority to get this sorted, as this bug restricts to use TF effectively to deploy NR resources?

**Comment by mbazhlekova** [comment] 2023-02-08 16:05
@getnilay I'm going to look into this issue more today. From what I remember, it's from the API and we're limited on what we can do from the Terraform side.

**Comment by sanderblue** [comment] 2023-02-10 18:16
We've prioritized this and are currently looking into this. So far I've been able to create at least 300 synthetics monitors during a single `terraform apply`.  

![Screen Shot 2023-02-10 at 11 55 54 AM](https://user-images.githubusercontent.com/2590905/218165955-35f999e6-7dca-4589-9724-f18ca4f27116.png)

![Screen Shot 2023-02-10 at 11 58 25 AM](https://user-images.githubusercontent.com/2590905/218165915-e5144c68-9215-481c-a0a5-022a253cf485.png)

It wasn't until I tried to create **_500 monitors_** that I saw any sort of error and now I see at least one of each of the errors that have been reported here. 

In the meantime, for those running into the tags error `Error: TAGGING_ERROR: An unknown error occurred while adding tag(s) to monitor`, I wonder if you could add tags to the monitors using the `newrelic_entity_tags` resource. Hopefully that might help avoid at least one of the errors.

As for the private location data source, try adding `account_id` to the data source attributes to help make the search for the location more granular. It's just a hunch that it might potentially help fetch the location more efficiently thus benefiting the overall operation.

i.e.
```hcl
data "newrelic_synthetics_private_location" "foo" {
  name = "name-of-private-location"
  account_id = var.account_id
}
```

We will likely need to talk to the Synthetics API team to help them fully understand the context of the issue because there's not much we can do on the Terraform side to "fix" this. Thanks for the patience with this one.

**Comment by wuetz** [comment] 2023-02-23 13:53
Hi all,

i had the very same behaviour like in the initial description. Luckily i just tested with newrelic provider version `3.14.0` and at least for me this failure seems to be gone.. 
Could anyone else confirm this?

**Comment by getnilay** [comment] 2023-02-28 05:47
@wuetz - I deployed multiple synthetics with `3.14.0` and in fact with `3.13.0` as well and don't see those issues highlighted above anymore, so looks like it's sorted now.

**Comment by NSSPKrishna** [comment] 2023-02-28 15:31
Thanks for letting us now, if the issue comes up again please file a new issue. We are closing this for now.

**Closed by NSSPKrishna** 2023-02-28 15:31 UTC
Labels: bug, upstream, group-synthetics

**Comment by jghiloni** [comment] 2023-06-07 21:41
I am seeing this with provider `3.24.0`, backleveling to `3.14.0` results in the problem not appearing.

**Comment by louhnmn** [comment] 2023-08-16 11:46
`3.25.0` here also
