### ISSUE TITLE
Unable to exclude Location_Private when not required

### ISSUE THREAD

**Issue by Jattwood90** [newrelic/terraform-provider-newrelic#2367] opened 2023-05-10 13:09 UTC
Hi there,

Attempting to implement this resource as a module: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/synthetics_script_monitor

I can successfully execute a plan when I have arguments for `location_private` and pass a null argument to the `locations_public`, but not the other way around. Docs say both are required but realistically we're likely to have users want to deploy to one or the other or both.

### Terraform Version
terraform `v.1.4.4`
provider `v.3.22.0`

### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_synthetics_script_monitor`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```hcl
//synthetics.tf
resource "newrelic_synthetics_script_monitor" "monitor" {
  status           = var.status
  name             = var.name
  period           = var.period
  type             = "SCRIPT_API"
  //script details
  script = var.script
  script_language                         = var.script_language
  runtime_type                            = var.runtime_type
  runtime_type_version                    = var.runtime_type_version  


  locations_public = var.locations_public
  
  location_private  {
    guid  = var.location_private_guid
    vse_password = var.location_private_vse_password
  }

  dynamic "tag" {
    for_each = var.tags
    
    content {
        key    = tag.value.key
        values = tag.value.values
    }
    }
  }

```

```hcl
//variables.tf
variable "status" {
  type    = string
  default = "ENABLED"
}

variable "name" {
  type    = string
  description = "Name of monitor"
}

variable "period" {
  type    = string
  default = "EVERY_10_MINUTES"
}

variable "script" {
  type    = string
  description = "(Required) Script you want to run to validate monitor."
} 

variable "script_language" {
  type    = string
  default = null
  description = "(Optional) The programing language that should execute the script."
}

variable "runtime_type" {
  type    = string
  default = null
  description = " (Optional) The runtime type that the monitor will run. Go with CHROME_BROWSER"
}

variable "runtime_type_version" {
  type    = string
  default = null
  nullable = true
  description = "The runtime type that the monitor will run."
}


//locations
variable "locations_public" {
  type    = list(string)
  default = null
  nullable = true
  
}


variable "location_private_guid" {
  type    = string
  description = "guid for private location"
  default = null
  nullable = true
}

variable "location_private_vse_password" {
  type    = string
  default = null
  nullable = true
}

//tags
variable "tags" {
  type = list(object({
    key = string
    values = list(string)
  }))
  description = "Key/value pairs"
  default = null
}


```

```hcl
//parameters.tfvars
// It can take up to 10 minutes for a private location to become available.
status = "ENABLED"
name = "TEST-TF-MONITOR-DEPLOY-API"
period = "EVERY_10_MINUTES"

script                                  = "$browser.get('https://one.newrelic.com')"
script_language                         = "JAVASCRIPT"
runtime_type_version                    = "100" //browser
runtime_type                            = "CHROME_BROWSER"
locations_public = ["AP_SOUTH_1", "AP_EAST_1"]

# location_private_guid = ""
# location_private_vse_password = false


tags = [
    {
        key = "UNIT"
        values = ["DEVELOPMENT"]
    }
]

```

### Actual Behavior
After executing a plan, I receive the following error:
`The argument "location_private.0.guid" is required, but no definition was found.`

### Expected Behavior
Provider should recognise there's a `locations_public` argument and ignore the `location_private` arguments, as it does in the reverse order.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -var-file=parameters.tfvars`

### Debug Output
See gist: https://gist.github.com/Jattwood90/9f47e910f9d36e123d8ba0822a53b55c

**Comment by pranav-new-relic** [comment] 2023-05-10 16:21
Hi @Jattwood90 - thank you for reporting this issue, and the detailed instructions on reproducing it :) we'll take a look into this soon, based on priority.

**Comment by pranav-new-relic** [comment] 2023-05-17 16:15
HI @Jattwood90, I've tried reproducing this and have had a word with my colleagues in the engineering team. Firstly - thanks for letting us know about the mistake in the documentation - we'll update it at the soonest.

About the `null` argument - since `locations_public` isn't a nested argument while `location_private` is, you see that the case you've mentioned in the description works but not the other way round, because upon definition, `location_private` requires a mandatory `guid` argument which cannot be made null/optional, given the schema that the configuration needs to abide by; which would mean, if `location_private` is not needed, making it `null` would possibly not be a solution (in this case, considering its nested structure and a mandatory `guid`) but should not make it to the Terraform configuration at all.

Though Terraform supports specifying the contents of a resource conditionally using arguments such as [`count`](https://developer.hashicorp.com/terraform/language/meta-arguments/count#using-expressions-in-count) and `for_each` with a [`dynamic`](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks) resource - Terraform just doesn't have enough support to conditionally include/exclude arguments inside a given resource using any of the aforementioned (as you may already know), which is why we see this as more of a Terraform limitation, and not a bug that can be fixed, given the usecase of generalising one Terraform configuration/script to two scenarios (one with only `public_locations` and one with only `private_location(s)`).

A possible solution can be to have two different resources defined to cater to each of the two scenarios, of which either of the two would be created "conditionally", based on the value of a variable; this would help exclude `private_location` from the configuration when it is not needed. Unfortunately, this is all we can possibly propose at this point, given the limitation - thank you for reporting this.

**Comment by pranav-new-relic** [comment] 2023-05-23 13:15
@Jattwood90 - right. Thanks for taking a look

**Comment by pranav-new-relic** [comment] 2023-05-24 05:25
Closing this issue, as the technical feasibility of this has been discussed in the thread and acknowledged accordingly.

**Closed by pranav-new-relic** 2023-05-24 05:25 UTC
Labels: group-general
