### ISSUE TITLE
newrelic_workflow Error: Cannot query field "aiWorkflows" on type "Account".

### ISSUE THREAD

**Issue by jgilfoil** [newrelic/terraform-provider-newrelic#2355] opened 2023-05-01 20:28 UTC
- [x] Your New Relic `provider` [configuration](#terraform-configuration-files) (sensitive details redacted)
- [x] A list of [affected resources](#affected-resources) and/or data sources
- [x] The [configuration](#terraform-configuration-files) of the resources and/or data sources related to the bug report (i.e. from the list mentioned above)
- [x] Description of the [current behavior](#actual-behavior) (the bug)
- [x] Description of the [expected behavior](#expected-behavior)
- [x] Any related [log output](#debug-output)

### Terraform Version
```sh
/app # terraform -v
Terraform v1.4.6
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `newrelic_workflow`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
provider.tf:
```hcl
terraform {
  backend "http" {
  }
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.21.1"
    }
  }
}

provider "newrelic" {
  account_id = <redacted>
}
```
relevant parts of main.tf:
```hcl
locals {
    email_upa_pro_notifications_list = "email@blah.com"
    slack_upa_pro_alerts_channel     = "<redacted>"
    slack_destination_id   = "<redacted>"
}

resource "newrelic_workflow" "upa_pro" {
  name = "UPA PRO - MaC"
  muting_rules_handling = "NOTIFY_ALL_ISSUES"

  issues_filter {
    name = "UPA-Pro-${upper(var.stack)}"
    type = "FILTER"

    predicate {
      attribute = "labels.policyIds"
      operator = "EXACTLY_MATCHES"
      values = [ 
        module.newrelic_cloudwatch_kinesis_alert_condition.alert_policy_id,
        ...
        <truncated>
        ...
        module.newrelic_upa_alert_conditions.alert_policy_id
        ]
    }
  }

  destination {
    channel_id = newrelic_notification_channel.email_upa_pro.id
  }

  destination {
    channel_id = newrelic_notification_channel.slack_upa_pro.id
  }
}

## Email Notification Setup
#
resource "newrelic_notification_destination" "email_upa_pro" {
  name = "upa-pro"
  type = "EMAIL"

  property {
    key = "email"
    value = local.email_upa_pro_notifications_list
  }
}

resource "newrelic_notification_channel" "email_upa_pro" {
  name = "email-upa-pro"
  type = "EMAIL"
  destination_id = newrelic_notification_destination.email_upa_pro.id
  product = "IINT" 

  property {
    key = "subject"
    value = "${upper(var.stack)} {{ issueTitle }}"
  }
}

#
## End of Email Notification Setup

## Slack Notifications Setup
#
data "newrelic_notification_destination" "slack_upa_pro" {
  id = local.slack_destination_id
}

resource "newrelic_notification_channel" "slack_upa_pro" {
  name = "slack-upa-pro"
  type = "SLACK"
  destination_id = data.newrelic_notification_destination.slack_upa_pro.id
  product = "IINT"

  property {
    key = "channelId"
    value = local.slack_upa_pro_alerts_channel
  }

  property {
    key = "customDetailsSlack"
    value = "UPA ${upper(var.stack)} Environment"
  }
}

#
## End of Slack Notifications Setup

```

### Actual Behavior
What actually happened?
```
/app # terraform plan
provider.newrelic.api_key
  Enter a value: <redacted>

module.newrelic_mwaa_alert_conditions.newrelic_alert_policy.mwaa: Refreshing state... [id=4312179]
module.newrelic_elasticsearch_alert_conditions.newrelic_alert_policy.elasticsearch: Refreshing state... [id=4312176]
module.newrelic_db_alert_conditions.newrelic_alert_policy.db: Refreshing state... [id=4312175]
module.newrelic_elb_alert_conditions.newrelic_alert_policy.elb: Refreshing state... [id=4312181]
module.newrelic_kafka_alert_conditions.newrelic_alert_policy.kafka: Refreshing state... [id=4312172]
module.newrelic_elasticache_alert_conditions.newrelic_alert_policy.elasticache: Refreshing state... [id=4312174]
module.newrelic_cloudwatch_kinesis_alert_condition.newrelic_alert_policy.this[0]: Refreshing state... [id=4312178]
module.newrelic_dms_alert_conditions.newrelic_alert_policy.dms: Refreshing state... [id=4312177]
newrelic_notification_destination.email_upa_pro: Refreshing state... [id=b4c395ad-85c0-472b-81c6-45634024cdb0]
module.newrelic_upa_alert_conditions.newrelic_alert_policy.this[0]: Refreshing state... [id=4312173]
data.newrelic_notification_destination.slack_upa_pro: Reading...
data.newrelic_notification_destination.slack_upa_pro: Read complete after 0s [id=7453e7e5-1da9-404e-848d-522acae4c955]
module.newrelic_lambda_alert_conditions.newrelic_alert_policy.lambda: Refreshing state... [id=4312171]
module.newrelic_eks_alert_conditions.newrelic_alert_policy.eks: Refreshing state... [id=4312180]
module.newrelic_upa_alert_conditions.newrelic_synthetics_script_monitor.custodian_accounts[0]: Refreshing state... [id=MjI4MjExN3xTWU5USHxNT05JVE9SfGM5MjQzOTFiLTc3YmYtNDBiZi1iMGMwLTM5ZTYwNmVkMGMwYw]
newrelic_notification_channel.email_upa_pro: Refreshing state... [id=ccd4cc1b-1441-41fb-87ad-5b7ccc3e9a46]
newrelic_notification_channel.slack_upa_pro: Refreshing state... [id=4c929dbd-0d1d-47ba-a532-550fcfa253e5]
module.newrelic_kafka_alert_conditions.newrelic_nrql_alert_condition.kafka_disk_usage[0]: Refreshing state... [id=4312172:31900865]
module.newrelic_kafka_alert_conditions.newrelic_nrql_alert_condition.kafka_cpu_utilization[0]: Refreshing state... [id=4312172:31900862]
module.newrelic_mwaa_alert_conditions.newrelic_nrql_alert_condition.dag_failure[0]: Refreshing state... [id=4312179:31900890]
module.newrelic_cloudwatch_kinesis_alert_condition.newrelic_nrql_alert_condition.cloudwatch_newrelic_integration: Refreshing state... [id=4312178:31900889]
module.newrelic_dms_alert_conditions.newrelic_nrql_alert_condition.dms_avg_cpu_utilization[0]: Refreshing state... [id=4312177:31900886]
module.newrelic_dms_alert_conditions.newrelic_nrql_alert_condition.dms_avg_write_latency[0]: Refreshing state... [id=4312177:31900887]
module.newrelic_dms_alert_conditions.newrelic_nrql_alert_condition.dms_avg_read_latency[0]: Refreshing state... [id=4312177:31900888]
module.newrelic_elasticache_alert_conditions.newrelic_nrql_alert_condition.elasticache_evictions[0]: Refreshing state... [id=4312174:31900878]
module.newrelic_elasticache_alert_conditions.newrelic_nrql_alert_condition.engine_cpu_utilization[0]: Refreshing state... [id=4312174:31900876]
module.newrelic_elasticache_alert_conditions.newrelic_nrql_alert_condition.key_authorization_failures[0]: Refreshing state... [id=4312174:31900877]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.rds_max_connections[0]: Refreshing state... [id=4312175:31900870]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.rds_free_local_storage_mb[0]: Refreshing state... [id=4312175:31900866]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.dynamodb_throttled_read[0]: Refreshing state... [id=4312175:31900871]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.dynamodb_throttled_requests[0]: Refreshing state... [id=4312175:31900863]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.rds_read_latency[0]: Refreshing state... [id=4312175:31900868]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.rds_avg_cpu_utilization[0]: Refreshing state... [id=4312175:31900869]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.rds_write_latency[0]: Refreshing state... [id=4312175:31900875]
module.newrelic_db_alert_conditions.newrelic_nrql_alert_condition.dynamodb_user_errors[0]: Refreshing state... [id=4312175:31900874]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_node_cpu_utlization: Refreshing state... [id=4312176:31900882]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_cluster_health_yellow[0]: Refreshing state... [id=4312176:31900885]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_cluster_health_red[0]: Refreshing state... [id=4312176:31900881]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_node_free_storage: Refreshing state... [id=4312176:31900880]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_node_old_jvm_pressure[0]: Refreshing state... [id=4312176:31900884]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_master_node_cpu_utlization[0]: Refreshing state... [id=4312176:31900879]
module.newrelic_elasticsearch_alert_conditions.newrelic_nrql_alert_condition.es_node_jvm_pressure[0]: Refreshing state... [id=4312176:31900883]
module.newrelic_elb_alert_conditions.newrelic_nrql_alert_condition.elb_5xx_errors[0]: Refreshing state... [id=4312181:31900897]
module.newrelic_elb_alert_conditions.newrelic_nrql_alert_condition.elb_target_response_time[0]: Refreshing state... [id=4312181:31900896]
module.newrelic_eks_alert_conditions.newrelic_nrql_alert_condition.eks_crashloop_backoff[0]: Refreshing state... [id=4312180:31900893]
module.newrelic_eks_alert_conditions.newrelic_nrql_alert_condition.eks_orphaned_load_balancer_ingress[0]: Refreshing state... [id=4312180:31900892]
module.newrelic_eks_alert_conditions.newrelic_nrql_alert_condition.eks_node_avg_cpu_utilization[0]: Refreshing state... [id=4312180:31900894]
module.newrelic_lambda_alert_conditions.newrelic_nrql_alert_condition.lambda_function_errors[0]: Refreshing state... [id=4312171:31900867]
module.newrelic_eks_alert_conditions.newrelic_nrql_alert_condition.eks_lb_controller_errors[0]: Refreshing state... [id=4312180:31900891]
module.newrelic_eks_alert_conditions.newrelic_nrql_alert_condition.alb_target_unhealthy[0]: Refreshing state... [id=4312180:31900895]
module.newrelic_lambda_alert_conditions.newrelic_nrql_alert_condition.lambda_function_throttled[0]: Refreshing state... [id=4312171:31900864]
module.newrelic_upa_alert_conditions.newrelic_synthetics_alert_condition.custodian_accounts[0]: Refreshing state... [id=4312173:31900898]
newrelic_workflow.upa_pro: Refreshing state... [id=b952c64a-e5d1-4b4b-a215-cc5a7650a394]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Cannot query field "aiWorkflows" on type "Account".
│ 
│   with newrelic_workflow.upa_pro,
│   on notifications.tf line 7, in resource "newrelic_workflow" "upa_pro":
│    7: resource "newrelic_workflow" "upa_pro" {

```
### Expected Behavior
Plan should run to success. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
This configuration was working yesterday with no changes to the tf configuration. Tried upgrading from provider 3.20 to the latest provider version(3.21.2), no change. Tried using latest version of terraform, also no change.

### Debug-Output
https://gist.github.com/jgilfoil/eaf8e708c0d64874659348c3e8ee6e4c

**Comment by strahinjapetrovic** [comment] 2023-05-01 20:52
I have the same problem!

**Comment by IliaShurygin** [comment] 2023-05-02 08:46
This is a duplicate of https://github.com/newrelic/terraform-provider-newrelic/issues/2354

The issue has been resolved, please see my comment in the linked issue

**Closed by IliaShurygin** 2023-05-02 08:46 UTC
Labels: group-workflows
