### ISSUE TITLE
newrelic_nrql_drop_rule deploying but not appearing in New Relic web UI

### ISSUE THREAD

**Issue by elenafayethomas** [newrelic/terraform-provider-newrelic#2243] opened 2023-02-13 17:20 UTC
Hi, please find the details of my issue below:

### Terraform Version
`Terraform v1.3.3`

### Affected Resource(s)
- `newrelic_nrql_drop_rule`

### Terraform Configuration
Variables are pulled in from `.auto.tfvars`
```hcl
terraform {
  required_version = "~> 1.0"
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.6"
    }
  }
}

provider "newrelic" {
  account_id = var.nr_account_id
  api_key    = var.nr_account_key
  region     = var.nr_region           # Valid regions are US and EU
}
```

And the example code (I ran this alongside my actual code to see if it was an issue with my main code. I encountered the same issue with the below code).
```hcl
resource "newrelic_nrql_drop_rule" "dropfilter_test" {
  description = "test description"
  action      = "drop_data"
  nrql        = "SELECT * FROM Logs WHERE newrelic.source = 'test123'
}

```

### Actual Behavior
On deploying a `newrelic_nrql_drop_rule`, `terraform apply` runs okay but the drop filter does not appear in the New Relic UI.

### Expected Behavior
The drop filter should have appeared in the New Relic UI.

### Steps to Reproduce
1. `terraform apply`

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Important Factoids
Running in WSL, deploying from local to New Relic. I also see that there is an issue with [the API](https://docs.newrelic.com/docs/logs/ui-data/drop-data-drop-filter-rules/#nerdgraph) where drop filters are not displayed unless you change an attribute. I am unsure whether the same issue applies here?

**Comment by NSSPKrishna** [comment] 2023-02-14 08:36
Hi @elenafayethomas, thanks for raising the issue. The API team is unable to add this to public. There isn't much to do on terraform side as it is working as intended. Closing this issue as it is a duplicate of #2152

**Closed by NSSPKrishna** 2023-02-14 08:36 UTC

**Comment by rcwsr** [comment] 2024-02-08 14:21
Why was this issue closed out of interest? Seems like a bug that drop rules are not displaying in the UI. I can see the drop rules fine in terraform but it would be nice if my colleagues could see them in the LogDropFilters UI, surely? @NSSPKrishna

**Comment by rcwsr** [comment] 2024-02-23 15:06
I can now see drop filters in the UI, did something change - very happy if it did! @NSSPKrishna
