### ISSUE TITLE
api.newrelic.com/graphql fails cause inconsistent TF state

### ISSUE THREAD

**Issue by chlos** [newrelic/terraform-provider-newrelic#2594] opened 2024-03-05 15:39 UTC
Hi there,

We often face the following error when running TF apply:
```
Error: POST https://api.newrelic.com/graphql giving up after 4 attempt(s): Post "https://api.newrelic.com/graphql": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

After that the following situation is possible:
* the changes are committed to `terraform.tfstate` but not published to New Relic
* if we try to apply changes one more time, TF can't see any new changes, because it consider them applied:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Terraform Version
1.1.4

**Comment by pranav-new-relic** [comment] 2024-03-18 04:02
Closing this issue as this is being looked into via other channels, since this is not a Terraform Provider specific issue (stems out of NerdGraph) and is possibly caused by intermittent API/network issues/an insufficient timeout limit.

**Closed by pranav-new-relic** 2024-03-18 04:02 UTC
