### ISSUE TITLE
`newrelic_notification_channel` data block

### ISSUE THREAD

**Issue by Will-1** [newrelic/terraform-provider-newrelic#2410] opened 2023-07-04 15:47 UTC
### Feature Description
The `newrelic_alert_channel` data block has now been deprecated. 
We need an equivalent data block for the `newrelic_notification_channel` to enable attaching alert policies to existing notification channels via workflows.

I understand these can be linked if all the resources are created within one file/module. 
We have a shared module for creating individual policies and workflows, but we would like to use a common channel/destination. Hence, the creation of policy does not have direct access to the channels.

i.e.
Shared module for creating alert policies and workflows
```
resource "newrelic_alert_policy" "alert_policy" {
 ...
}

resource "newrelic_nrql_alert_condition" "policy_condition" {
  ...
}

resource "newrelic_workflow" "workflow" {
   ...
  destination {
    channel_id = newrelic_notification_channel.email-channel.id
  }
}

//This is the missing block
data "newrelic_notification_channel" "email-channel" {
  ...
}
```

Common channel/destination setup
```
resource "newrelic_notification_channel" "onesearch-email-channel" {
  ...
}

resource "newrelic_notification_destination" "email-destination" {
  ...
}

resource "newrelic_notification_channel" "pagerduty-channel" {
  ...
}

resource "newrelic_notification_destination" "pagerduty-destination" {
  ...
}
```

### Additional context
This is a major blocker for us on alerting

**Comment by stevula** [comment] 2023-07-04 22:45
The "Getting Started" guide covers this use case under ["Add a notification channel"](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/getting_started#add-a-notification-channel). It may also be helpful to reference https://github.com/newrelic/terraform-provider-newrelic/issues/2286#issuecomment-1560860973.

**Comment by Will-1** [comment] 2023-07-05 09:34
> The "Getting Started" guide covers this use case under ["Add a notification channel"](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/guides/getting_started#add-a-notification-channel). It may also be helpful to reference [#2286 (comment)](https://github.com/newrelic/terraform-provider-newrelic/issues/2286#issuecomment-1560860973).

Thanks for the quick response, I have updated my description to more clearly explain why we require a data block. I understand these can all be linked if created together, but I would like to avoid creating the same channels over and over.

**Comment by RavitejaSurampudi** [comment] 2023-07-06 11:29
@Will-1 Thank you for reaching out to us!
At present  new relic provider doesnt have the data source for the resource **newrelic_notification_channel**. I will add this as a enhancement in our upcoming sprint and update here once available.

**Comment by IliaShurygin** [comment] 2023-07-31 10:36
Hi @Will-1!

Currently, `newrelic_notification_channel` can unfortunately only be used by a single workflow at a time. Even if you could use a data source to fetch a channel id, you would not be able to add it to another workflow. 

What you can reuse is [newrelic_notification_destination](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination) that contains all the credentials and settings needed to reach the notification destination. 

Destinations do have [a data source](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/notification_destination) already that allows you to fetch them by id or name. Please do let us know if there are other destination fields you would like to use in the data source as well.

**For your particular example,** I would just move `newrelic_notification_channel` resource to the alert policy TF config and treat it as a part of the workflow configuration. You can use destination data source to fetch the destination from the second config.

----

We do understand that the current situation where channels cannot be reused is confusing and consider a number of different options on how to make it better. Making channels reusable channels is one of the options, but I cannot guarantee that this is what we are going to go with.

----

I am going to close this issue as it essentially a duplicate of #2067. 
if we are going to allow to reuse channels at some point, there is going to be a data source to fetch them. 

But until channels are reusable, having a data source sounds like something that would only add more confusion.

Please do not hesitate to reopen this issue if you see a use-case for the non-reusable notification channel data source, but please do include an example.

**Closed by IliaShurygin** 2023-07-31 10:36 UTC
Labels: enhancement, group-notifications
