### ISSUE TITLE
newrelic_one_dashboard is no longer working as of today

### ISSUE THREAD

**Issue by bgridley** [newrelic/terraform-provider-newrelic#2499] opened 2023-10-25 21:16 UTC
### Terraform Version
Terraform v1.1.7
provider registry.terraform.io/newrelic/newrelic v3.27.3

### Affected Resource(s)
- `newrelic_one_dashboard`

### Terraform Configuration
> Please include your `provider` configuration (sensitive details redacted) as well as the configuration of the resources and/or data sources related to the bug report.
```
provider "newrelic" {
  api_key    = 12345
  account_id = 12345
  region     = "US"
}
terraform {
  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~>3.27.3"
    }
  }
  backend "gcs" {}
}
```

```
variable "service_name" {
  type = string
  default = "test-service"
}
resource "newrelic_one_dashboard" "with-db" {
    name = "testing_this"
    description = null
    permissions = "public_read_only"
    page {
        name = "testing_this"
        widget_area {
            title = "Duration"
            column = 1
            height = 3
            row = 4
            width = 4
            nrql_query {
                query = "SELECT average(databaseDuration), average(externalDuration), average(duration - databaseDuration - externalDuration) as CodeExecutionTime FROM Transaction TIMESERIES 1 minute SINCE 3 hours ago WHERE appName = '${var.service_name}'"
            }
        }
    }
}
```
### Actual Behavior
When running terraform import to import an existing dashboard or terraform plan with existing dashboards in the terraform state file I get the following error

```
2023-10-25T21:10:13.978Z [ERROR] vertex "import newrelic_one_dashboard.with-db result" error: Cannot query field "variables" on type "DashboardEntity".
2023-10-25T21:10:14.129Z [ERROR] provider.terraform-provider-newrelic_v3.13.0: Response contains error diagnostic: diagnostic_severity=ERROR diagnostic_summary="Cannot query field "variables" on type "DashboardEntity"." tf_provider_addr=provider tf_req_id=6583fa23-3532-6a11-8520-887e89907dee @module=sdk.proto diagnostic_detail= tf_proto_version=5.3 tf_resource_type=newrelic_one_dashboard tf_rpc=ReadResource @caller=/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/diag/diagnostics.go:56 timestamp=2023-10-25T21:10:13.964Z
2023-10-25T21:10:14.129Z [ERROR] vertex "newrelic_one_dashboard.with-db (import id \"dashbaordID\")" error: Cannot query field "variables" on type "DashboardEntity".
╷
│ Error: Cannot query field "variables" on type "DashboardEntity".
│
│
╵
```

### Expected Behavior
No configuration was changed, I expected terraform plan to run showing no changes. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import newrelic_one_dashboard.with-db dashboardID`

### Debug Output
NA

### Panic Output
NA

### Important Factoids
Worked earlier today, now it doesn't work, with 0 changes. 

### References
NA

**Comment by jakewan** [comment] 2023-10-25 21:20
Perhaps related: https://github.com/newrelic/terraform-provider-newrelic/issues/2354#issuecomment-1531092968

**Comment by mbazhlekova** [comment] 2023-10-25 21:24
@bgridley I'm going to take a look at this shortly

**Comment by mbazhlekova** [comment] 2023-10-25 21:48
Looks like it's an issue from the Dashboard API. I've alerted the team that we're seeing these errors.

**Comment by mbazhlekova** [comment] 2023-10-25 22:29
@bgridley  Issue should be resolved now. Let me know if you're still seeing this error.

**Comment by jakewan** [comment] 2023-10-25 23:12
@mbazhlekova Would it make sense to add an incident report to [New Relic Status - Incident History](https://status.newrelic.com/history)? I have a feeling this affected many users.

**Comment by cfunston** [comment] 2023-10-25 23:23
@jakewan Just FYI, this also broke our deployments and I found this issue while investigating the problem.

**Comment by jakewan** [comment] 2023-10-25 23:28
@cfunston Same here. It really called out the need to keep supporting resources like these in a separate infrastructure stack from mission-critical ones. I definitely learned an important lesson today.

**Comment by pranav-new-relic** [comment] 2023-10-27 05:59
HI everyone, sorry about the inconvenience caused. This was caused by a glitch on the API front, which was fixed yesterday. Thank you for all of your inputs - we shall be closing this issue as it has been fixed.

**Closed by pranav-new-relic** 2023-10-27 05:59 UTC
