### ISSUE TITLE
Version v2.50.0 is gone missing

### ISSUE THREAD

**Issue by ntwairay** [newrelic/terraform-provider-newrelic#1966] opened 2022-08-30 07:46 UTC
Hi All,

The tag for V2.50.0 is gone missing. Would you please retag it back ?

Regards

Ray

<img width="1502" alt="Screen Shot 2022-08-30 at 5 45 55 pm" src="https://user-images.githubusercontent.com/25917164/187379969-91a38e6b-136a-4b1f-9124-c182a527e644.png">

**Comment by kidk** [comment] 2022-08-30 08:28
We had to rollback a release, for more info check: https://github.com/newrelic/terraform-provider-newrelic/issues/1962 

Closing this one as it's a duplicate of #1962

**Closed by kidk** 2022-08-30 08:28 UTC
