### ISSUE TITLE
`newrelic_entity` data source doesn't find entity in sub-account

### ISSUE THREAD

**Issue by Tensho** [newrelic/terraform-provider-newrelic#2425] opened 2023-07-17 16:40 UTC
Recently I started to split organisation's single account into client-specific sub-accounts. I found out that the current `newrelic_entity` data source filter doesn't work, so I've added `accountID` tag filter to it as recommended in the [doc](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/entity). However, despite NewRelic API returns expected response, provider resource doesn't accept it and returns "not found" error.

### Terraform Version

```
$ terraform -v
Terraform v1.1.6
on darwin_arm64
+ provider registry.terraform.io/newrelic/newrelic v3.25.2
```

### Affected Resource(s)

- [`newrelic_entity` data source](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/entity)

### Terraform Configuration

```hcl
data "newrelic_account" "default" {
  count = var.newrelic_enabled ? 1 : 0

  name = "Acme Inc" # sub-account
}


data "newrelic_entity" "apm" {
  count = var.newrelic_enabled ? 1 : 0

  name       = "ABC"
  type       = "APPLICATION"
  domain     = "APM"

  tag {
    key   = "accountID"
    value = data.newrelic_account.default[0].id
  }
}
```

### Actual Behavior

```
│ Error: no entities found for the provided search parameters, please ensure your schema attributes are valid
```

### Expected Behavior

The provider processes API response correctly.

### Steps to Reproduce

1. `terraform apply`

### Debug Output

```
2023-07-17T17:15:41.045+0100 [INFO]  provider.terraform-provider-newrelic_v3.25.2: 2023/07/17 17:15:41 [DEBUG] newrelic API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Mon, 17 Jul 2023 16:15:40 GMT
Proxied-By: Service Gateway
Served-By: nerd-graph
Server: envoy
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: accept-encoding
X-Envoy-Upstream-Service-Time: 303

2d9
{
 "data": {
  "actor": {
   "entitySearch": {
    "count": 1,
    "query": "name = 'ABC' AND domain = 'APM' AND type = 'APPLICATION' AND tags.`accountID` = '12345678'",
    "results": {
     "entities": [
      {
       "__typename": "ApmApplicationEntityOutline",
       "accountId": 12345678,
       "alertSeverity": "NOT_CONFIGURED",
       "applicationId": 1230940855,
       "domain": "APM",
       "entityType": "APM_APPLICATION_ENTITY",
       "guid": "NDAxOTY4NHxBUE18QVBQTElDQVRJT058MTIzMDk0MDg1NQ",
       "indexedAt": 1689609074704,
       "language": "ruby",
       "name": "ABC",
       "permalink": "https://one.newrelic.com/redirect/entity/NDAxOTY4NHxBUE18QVBQTElDQVRJT058MTIzMDk0MDg1NQ",
       "reporting": true,
       "type": "APPLICATION"
      }
     ],
     "nextCursor": null
    },
    "types": [
     {
      "count": 1,
      "domain": "APM",
      "entityType": "APM_APPLICATION_ENTITY",
      "type": "APPLICATION"
     }
    ]
   }
  }
 }
}
0


```

As you may note the output is expected – 1 APM entity in the response `entities` list. The same result can be observed by querying the same criteria within NewRelic CLI:
```
$ newrelic entity search --domain APM --type APPLICATION --name ABC --tag accountID:12345678
{
  "account": {},
  "accountId": 12345678,
  "alertSeverity": "NOT_CONFIGURED",
  "apmBrowserSummary": {},
  "apmSummary": {},
  "applicationId": 1230940855,
  "dashboardTemplates": null,
  "domain": "APM",
  "entityType": "APM_APPLICATION_ENTITY",
  "goldenMetrics": {
    "context": {},
    "metrics": null
  },
  "goldenSignalValues": null,
  "goldenSignalValuesV2": {
    "signalValues": null,
    "timeIndex": null
  },
  "goldenTags": {
    "context": {},
    "tags": null
  },
  "guid": "NDAxOTY4NHxBUE18QVBQTElDQVRJT058MTIzMDk0MDg1NQ",
  "indexedAt": 1689609074704,
  "language": "ruby",
  "name": "ABC",
  "permalink": "https://one.newrelic.com/redirect/entity/NDAxOTY4NHxBUE18QVBQTElDQVRJT058MTIzMDk0MDg1NQ",
  "recommendedServiceLevel": {
    "indicators": null
  },
  "relatedDashboards": {
    "dashboardGuids": null,
    "dashboards": null
  },
  "reporting": true,
  "runningAgentVersions": {},
  "serviceLevel": {
    "indicators": null
  },
  "settings": {},
  "type": "APPLICATION",
  "uiTemplates": null
}
```

### Important Factoids

I run Terraform with USER API key created in the main (default) NewRelic organisation account (`10000000`), but the target entity resides in the sub-account (`12345678`). For some reason that works for NewRelic CLI, but not for Terraform provider (Go client returns an expected response).

### References

* [`newrelic_entity`](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/data-sources/entity)
* https://github.com/newrelic/terraform-provider-newrelic/issues/834

**Comment by pranav-new-relic** [comment] 2023-07-18 13:35
Hey @Tensho - I was just typing out a reply :)

**Comment by pranav-new-relic** [comment] 2023-07-18 13:43
Hi @Tensho, thank you for reporting this. The cause of this is a change (which you just identified above) we made to the `newrelic_entity` data source (which you would find with v3.24.1 and all subsequent versions of the Terraform Provider) to filter the API response by the `account_id` specified in the `provider{}` configuration used. Since you mention you're running it with the API key linked to `10000000` and the `account_id` as `10000000` while the entity resides in the subaccount `12345678`, and the provider filters entities returned by the `account_id` in the `provider{}` block, you see the not found error.

This change was made in order to cater to requests we obtained from users (such as https://github.com/newrelic/terraform-provider-newrelic/issues/1041, and #834 you've attached above) that the usage of this data source is confusing, given many users seem to have cases in which they have entities with the same name existing across an account and its subaccounts, in which case the API response has all of them, and the data source tends to return the entity in the subaccount, while they expect the entity returned to be that which corresponds to the `account_id` used in `provider{}`, and hence, this change was made. In summary - this is expected behaviour, so you might want to use the ID of the subaccount as the `account_id` to get the entity.

However, it appears that the documentation does not have adequate information about this behaviour of the data source, which is why you landed up using the tag filter too. I'll see how we can explain this better in the documentation, after a discussion with the team. Thank you for reporting this :)

**Comment by pranav-new-relic** [comment] 2023-07-18 16:48
Hi @Tensho - thanks for explaining your use case - it certainly is a unique one. The `newrelic_entity` data source is generally in use with accounts that are already created, since `newrelic_account_management` is a very recent addition, which is why the expected behaviour was thought of in the aforementioned format - so I'm not sure if we'd want to change this (probably, with the addition of an attribute to the data source which, if not specified, results in default behaviour but if specified, does not filter entities returned by the `account_id` in the `provider{}`, similar to what you've suggested).

I can open a conversation with my team soon to think into this, but we are currently occupied with other priorities too at the moment, unfortunately - so we wouldn't be able to roll this out anytime soon. However, I'll have to discuss with my team if it would be possible to cover this usecase too. I shall keep you posted after we have an update - thanks!

**Comment by Tensho** [comment] 2023-07-19 08:30
Yes, something like an extra data source attribute is precisely what I'm thinking of:
```
data "newrelic_entity" "foobar" {
  account_id = "12345678"
  ...
}
```
If you decide with the team it makes sense from the design point of view, I'm eager to spend my time and contribute to the code (I have some prior experience with other Terraform providers). Looking forward for your decision 🙇

**Comment by pranav-new-relic** [comment] 2023-07-20 11:04
Hi @Tensho - I've had a word with my team, and we might want to go ahead with this. We're open for a contribution you'd want to make, as it'll take us some time until we pick this up 😄 

We find your suggestion useful, and so, I think it would be ideal to proceed along the lines of what you've mentioned above; an optional attribute `account_id` in the data source.

In the code you've identified in one of your previous comments, i.e.

> Inspecting the code I found there is a condition which skips entities which have account ID different from the one used in the NewRelic client, e.g. configured via `NEW_RELIC_ACCOUNT_ID`:

the account ID used to filter entities from the API response would need to be the new `account_id` attribute you're going to add, if it is specified in the Terraform configuration, else, would need to default to the account ID used in the `provider{}` block, i.e. how it currently behaves. These are some hints I wanted to give - you can try this out 😄

**Comment by Tensho** [comment] 2023-07-20 11:40
@pranav-new-relic Thanks for green light with this, appreciate your inputs 🙇 I've already forked the repo and am looking around the CONTRIBUTION.md. Stay tuned for PR 🙂 

BTW, the doc says you have a Slack chat. Would you mind sharing it with me for a faster feedback loop if I am stuck somewhere on the road? My email is in the GitHub bio.

**Comment by Tensho** [comment] 2023-07-20 19:14
It took me a while to understand the license key's **account** overrides `NEW_RELIC_ACCOUNT_ID` env var value on [`newrelic.NewApplication()`](https://github.com/Tensho/terraform-provider-newrelic/blob/main/newrelic/provider_test.go#L183) call 😅 I've set `NEW_RELIC_ACCOUNT_ID` to parent account, but taken random license key from child account and couldn't figure out why it can't find the APM application eventually. IMHO, that behaviour is a bit counterintuitive.

**Comment by Tensho** [comment] 2023-07-20 19:22
The target [`TestAccNewRelicEntityData_EntityInSubAccount`](https://github.com/Tensho/terraform-provider-newrelic/blob/main/newrelic/data_source_newrelic_entity_integration_test.go#L85C6-L85C50) test fails because [account ID is hardcoded](https://github.com/Tensho/terraform-provider-newrelic/blob/main/newrelic/data_source_newrelic_entity_integration_test.go#L93), which is not portable 😞 I'll try to figure out how to make it dynamic.

**Comment by pranav-new-relic** [comment] 2023-07-21 04:12
Hi @Tensho - just to clarify on the license key part; the expected usage of the data source is that we specify a key belonging to the account specified in the configuration of `provider{}` (which is mostly how all other resources/data sources work too) - however, the changes you would want to make wouldn't need to depend on this 😄 modifying this condition to filter either by `account_id` in the configuration if specified, or the `account_id` in the `provider{}` (by default, if no `account_id` exists in the configuration) should suffice.

https://github.com/newrelic/terraform-provider-newrelic/blob/25be2450e58f944ffad08f1e06daf48a8c577e6c/newrelic/data_source_newrelic_entity.go#L131-L136

Also, the tests cases for this data source are a bit weird, given we need to have the same entity across multiple accounts/subaccounts for the tests to work, which is why we had to hardcode some of them (as the accounts comprising these entities on our end change sometimes). You can leave the tests over to me - I'll take a look whenever free next week.

Awaiting your submission - about the Slack conversation you mentioned, it's mostly for support teams to interact with New Relic customers, which we (on the engineering front) have very little (or no) idea about - so we shall continue to interact via this thread 😄 I'll keep taking a look whenever I'm free from other tasks in the next week - appreciate your patience :)

**Comment by Tensho** [comment] 2023-07-21 20:17
@pranav-new-relic Please take a look into [PR](https://github.com/newrelic/terraform-provider-newrelic/pull/2432) and assist with necessary acctest changes 🙇

**Comment by pranav-new-relic** [comment] 2023-07-25 04:20
Thank you for the contribution, @Tensho. I'll continue to look into this in the next couple of days (since we want to make sure this doesn't lead to a breaking change 😄 and we're looking into a couple of other things) and keep you posted when we're good to merge and get it released.

**Comment by Tensho** [comment] 2023-07-25 08:37
@pranav-new-relic Great, thanks for pushing it forward promptly 🙇 I'm looking forward to this feature as a big piece of my work depends on it 😅  If you need any help from my side please let me know.

**Comment by pranav-new-relic** [comment] 2023-07-25 16:38
@Tensho thanks - we're good for now; with the changes I've made, this should be fine. However, it'll take me some time to make sure this is okay with the team, just to ensure this would lead to no unexpected behaviour after the release (though it looks like a small change, and ideally, isn't expected to cause such impact 🙂). Please allow me some time as I get this done, since we're having to juggle a couple of other things too - I'll have a word with the team, and get the PR merged and pushed with the next release in the next 2-3 days. 

You can just help me out in the meanwhile, by testing the current code (in the PR, after my changes) if it works as expected to fetch an entity from the parent account by default, but from the subaccount when `account_id` is added. I know it works, but would love to get another pair of eyes 👀. Thanks!

**Comment by Tensho** [comment] 2023-07-25 16:43
@pranav-new-relic Sure, I understand you want to double-check the change to make sure it doesn't introduce any regression. I'll let you know how the current code in PR works at my end today.

**Comment by Tensho** [comment] 2023-07-25 16:55
@pranav-new-relic I can confirm the code in PR retrieves sub-account entity successfully when a provider is configured with the parent account.

I looked through the code and appreciated the elegance of your variant – overwrite `accountId` var with the optional configuration value in case it's specified. That's a simple and natural approach, much better than my nested conditions attempt 😅

**Comment by pranav-new-relic** [comment] 2023-07-25 17:04
Cool, thanks for taking a look! I'll continue to look into taking the PR forward tomorrow :)

**Closed** 2023-07-26 08:09 UTC
Labels: enhancement

**Comment by pranav-new-relic** [comment] 2023-07-26 08:52
v3.26.0 with this code addition is now out :)

**Comment by Tensho** [comment] 2023-07-26 09:27
@pranav-new-relic Much obliged with this uber-fast release 🙇
