### ISSUE TITLE
Create a NRQL condition with "cadence" streaming method fails

### ISSUE THREAD

**Issue by ZCNST** [newrelic/terraform-provider-newrelic#1655] opened 2022-02-15 18:46 UTC
Hi there,

I ran into the problem described below, I would like to know your thoughts on this and if you can help.

### Terraform Version
```sh
Terraform v0.14.0

Your version of Terraform is out of date! The latest version
is 1.1.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- `newrelic_nrql_alert_condition`

### Terraform Configuration

```hcl
resource "newrelic_nrql_alert_condition" "alert_condition_step_6_not_displayed" {
  policy_id = newrelic_alert_policy.alert_policy.id

  name                           = "The Confirmation Message is not displayed"
  enabled                        = true
  type                           = "static"
  value_function                 = "single_value"
  violation_time_limit_seconds   = 2592000
  fill_option                    = "last_value"
  runbook_url                    = var.runbook_url
  expiration_duration            = 7200
  close_violations_on_expiration = true
  aggregation_window             = 900
  aggregation_method             = "cadence"
  aggregation_delay              = 0

  critical {
    operator              = "above"
    threshold             = 0
    threshold_duration    = 3600
    threshold_occurrences = "at_least_once"
  }

  nrql {
    query = local.nrql_alert_condition_step_6_not_displayed
  }
}
```

### Actual Behavior

```
  on ../../modules/u/c/b/main.tf line 282, in resource "newrelic_nrql_alert_condition" "alert_condition_step_6_not_displayed":
 282: resource "newrelic_nrql_alert_condition" "alert_condition_step_6_not_displayed" {

settings.aggregationDelay: CADENCE requires the aggregation delay setting


Error: Validation Error: BAD_USER_INPUT
```

### Expected Behavior

The error suggests that the `settings.aggregationDelay` attribute is missing, but it is passed using   

```hcl
aggregation_method             = "cadence"
aggregation_delay              = 0
```

The expected result is that the `apply` command is successful

**Comment by kidk** [comment] 2022-02-25 08:59
Thanks for the report @ZCNST I've passed this on to our alert team as I'm not sure why this is happening.

**Comment by emetcalf9** [comment] 2022-03-03 00:02
I can reproduce this error when using `aggregation_delay = 0`, but if I use a non-zero value it does go through successfully.

It looks like the 0 is getting converted to `null` somewhere before the request to create the condition is made, so it looks like there was no aggregation_delay set. Still looking into exactly what is happening here, but using any value other than 0 should allow you to create the conditions now.

**Comment by kgrits** [comment] 2022-03-16 10:59
Similar behavior with event_flow aggregation method when aggregation_delay is set to 0.

```
Error: Validation Error: BAD_USER_INPUT
settings.aggregationDelay: Aggregation delay must be set for aggregation method EVENT_FLOW
```

**Comment by emetcalf9** [comment] 2022-03-18 17:10
PR created that will allow 0s in aggregation_delay. This will fix the issue for both `cadence` and `event_flow` methods because they use the same field. Closing this issue now!

**Closed by emetcalf9** 2022-03-18 17:10 UTC
Labels: bug, group-alerts
